### PR TITLE
Add many (43) polys to Car and Car-dark layouts

### PR DESCRIPTION
**Pull request by jfitie**

### CODE REVIEW

**Comment by jfitie** [comment]
Before:
screenshot_2017-05-10-13-31-34

After:
screenshot_2017-05-10-13-31-14

**Comment by jfitie** [comment]
Before:
screenshot_2017-05-10-13-33-02

After:
screenshot_2017-05-10-13-33-16

**Comment by jfitie** [comment]
High in the sky :smile:

screenshot_2017-05-10-14-34-57

**Comment by sleske** [comment]
Looks nice, thanks! Could you rebase your pull request, to remove the spurious merge and revert from the history? Or should I do it when merging it?

**Comment by jfitie** [comment]
@sleske Please do, as I have no idea what you're talking about :laughing:
Just changed the order for the new features to `10-` for better performance at low zoom levels.

**Comment by sleske** [comment]
Ok, I'll try to get to it in the next days.

**Comment by sleske** [comment]
Ok, I'll try to get to it in the next days.

**Comment by sleske** [comment]
Merged (after cleanup) as commit  e91a4ca20da321be1131e004d5703a84b5496947 . Thanks!

**Pull request closed without merging**
