### PR TITLE
Fix:Core:Fix crash

### PR DESCRIPTION
**Pull request by jandegr**
fixes a crash in the following scenario

click a point on the map
set it as position with gui_internal
click the button that centers the map around your position

### CODE REVIEW

**Comment by metalstrolch** [comment]
Unable to merge this, as branch is outdated, but @jandegr doesn't give push permission on his branch.
@jandegr please update (and merge) your branch.

**Comment by jandegr** [comment]
I gave permissions, but why not use this one as a testcase for https://github.com/navit-gps/navit/issues/868

thx.

**Comment by jkoan** [comment]
> I gave permissions, but why not use this one as a testcase for #868
> 
> thx.

if the commit 43485aee2deaee06958a3465f74923f4aa199405 would follow the commit guidelines i could "rebase and merge" directly, but now i would need "Squash and merge" to give a new commit message

**Comment by jandegr** [comment]
Indeed, I just could fix the title to comply with https://navit.readthedocs.io/en/latest/development/commit_guidelines.html
I can't change the commit message myself anymore either, will close this one and open a new one for it.
But why was this not done correctly for so many of those other commits in trunk if it is so simple to deal with  https://github.com/navit-gps/navit/issues/868

**Pull request closed without merging**
