### PR TITLE
Inkscape svg2png

### PR DESCRIPTION
**Pull request by lufv**
Inkscape doesn't use --without-gui argument anymore

Thanks for contributing to Navit!
Before opening a pull request on navit, make sure your commit message follows our guidelines:
https://navit.readthedocs.io/en/trunk/development/commit_guidelines.html

and that your code is compliant with out coding style guidelines:
https://navit.readthedocs.io/en/trunk/development/programming_guidelines.html

### CODE REVIEW

**Comment by jkoan** [comment]
Hi @lufv 
Thank you for your work.
I saw the patch of Debian here: https://salsa.debian.org/debian/navit/-/blob/master/debian/patches/inkscape-1.0.patch
I think the Debian one would be more compleat, right?
Also, for me its more readable then your Solution.

**Comment by lufv** [comment]
> Hi @lufv
> Thank you for your work.
> I saw the patch of Debian here: https://salsa.debian.org/debian/navit/-/blob/master/debian/patches/inkscape-1.0.patch
> I think the Debian one would be more compleat, right?
> Also, for me its more readable then your Solution.

Yes, I think it looks okay!

**Comment by lufv** [comment]
I guess it also explains why I didn't get any PNG files after my patch. Will check if after this one it'll work

**Comment by jkoan** [comment]
Obsolete as of #1056

**Pull request closed without merging**
