### PR TITLE
Allow unusual building

### PR DESCRIPTION
**Pull request by metalstrolch**
This pull request updates navits cmake system to allow more unusual build and
install path configurations as well as renaming the navit binary. This
sis required for restricted environments like Sailfish OS harbour that
do not follow usual path conventions.

You can now:
redefine the binary name (NAVIT_BINARY)
control the translation file names (PACKAGE)
select the library directory (LIB_DIR)
select the share directory (SHARE_DIR)
select the locales directory (LOCALE_DIR)
select the images directory (IMAGE_DIR)
select the man directory (MAN_DIR)

the .desktop file is updated and the man file is renamed according to this and the install prefix is still honoured.

### CODE REVIEW

**Comment by zintor** [comment]
Thx for the pull request.
A question about the IMAGE_DIR as I am interested of making the SailfishOS build:
What about using more image paths e.g. "86x86", "108x108", "256x256",... Should these realized as an extra platform build or for all?

**Comment by metalstrolch** [comment]
I'm not an expert on habits for the navit project, but I would just add those icons to main line. Since this shouldn't hurt any other build. I plan to mainline the few things in sailfish_build branch too soon.
I can do this in the near future.

Not much effort is left to build for sailfish OS:
combine the branches trunk, allow_unusual_builds and sailfish_build, and you can build a (almost) harbour compatible rpm package for sailfish os device and emulator. (Check my "metalstrolch" fork for the "metalstrolch" branch, which contains exactly this combination) I'm doing packages that can be installed with pkcon on the device since december 2015

Currently I'm preparing a qt5_qml GUI skeleton. I'll do the linkage between the graphics part and the GUI. But I'll not do the real gui, as I'm not an QML expert and running out of time. Feel free to kick in there.

**Comment by metalstrolch** [comment]
@pgrandin could you check if this patch has any impact on android and windows builds? They build in ci, but i cannot check if everything is still fine.

**Comment by zintor** [comment]
I already use your "metalstrolch" fork for building the rpm package. I wrote a howto at the navit wiki on my user page.
The qt5_qml GUI skeleton will be great, as I would like to see a nice SFOS gui. :) I am willing to create the SFOS GUI for navit. After setting up my new hardware environment I will try my best to kick in.
Some harbour-navit icons are already done. image

**Comment by metalstrolch** [comment]
Merging this, as further work on QT5 depends on this. Hopefully this breaks nothing. Seems nobody has time to care about it.

**Pull request merged**
