### PR TITLE
Refactor:route:Improve documentation

### PR DESCRIPTION
**Pull request by mvglasow**
Signed-off-by: mvglasow <michael -at- vonglasow.com>

### CODE REVIEW

**Comment by sleske** [comment]
Thanks for improving the docs. Often overlooked, yet imporant 👍 .
And BTW: I don't think simple changes like this really need a PR. Just commit them to trunk - we can always fix any mistakes later.

**Comment by mvglasow** [comment]
@sleske afaik direct commits to trunk have been disabled, which leaves pull requests as the only option.

**Comment by sleske** [comment]
@mvglasow : Ah, I didn't know. Seems it does not apply to me, as I'm a team admin.
Personally, I think that is too restrictive. Feature branches (which PRs are) should be restricted to risky, disruptive changes, or if a discussion is desired. Having a PR for every trivial change just feels wrong.
I'm not sure where to bring this up, however - do you know how this was decided?

**Comment by mvglasow** [comment]
@sleske: @pgrandin added that a couple of weeks ago (in fact it seems I was the first to stumble across this, trying to push some documentation changes). We talked about this in IRC (https://irclogs.navit.ie/%23navit-2017-10-27.log) and I made some suggestions, but I didn’t follow up any more after that.

Which again raises the question: where would we discuss such things? There’s ticket #383, somewhat related; I would in fact favor trac for such discussions (feel free to CC me if you open a ticket).

**Comment by metalstrolch** [comment]
I would prefer Github, as I dont have ( and dont want to) have a Track account. Beside that you can easily refer things in Github. So why a double infrastructure!

**Comment by mvglasow** [comment]
@metalstrolch Trac was there before we switched to Github, and as a result, all tickets affecting Navit live there—so technically, Github issues are the redundant part in the infrastructure ;-) Trac supports OpenID with a number of authentication providers (Navit wiki as well as Google, among others, not sure about Github), thus you don’t need a separate account. I do see your point about Github references—maybe that can be added somehow. Though all of these are even more OT than the discussion about changes to trunk…

**Comment by sleske** [comment]
Well, it's really unfortunate that we have tickets both in Trac and in Github (issues). I initally opposed enabling issues in Github because of this, but I was overruled.
I think the best option at this point is to migrate the Trac issues to Github and shut down Trac (or make it readonly). But that's a different discussion...

**Comment by sleske** [comment]
As to the commit / merge rules:
As explained above, I strongly object to requiring PRs for everything.
I think we should continue the discussion in #383 . I'll add a comment there.

**Pull request merged**
