### PR TITLE
Add:graphics/windows: polygons with holes for windows CE

### PR DESCRIPTION
**Pull request by metalstrolch**
Add polygon with holes support for windows CE

### CODE REVIEW

**Comment by metalstrolch** [comment]
Untested on real windows CE device!
Needs to be confirmed working before merge!

**Comment by metalstrolch** [comment]
See  #861 for preprocessed map of Bavaria, as well as a test map showing only some test polygons.

**Comment by gefin** [comment]
search for Prien to find the location. 
It is a bit slow, but work.

**Comment by metalstrolch** [comment]
OK. Great to see it's working at least, and the drawing looks OK as far as I can see. It only places the zoom buttons wrong, but this is unlikely introduced by this change.

About the speed: is it actually slower than before introducing the multipolygons? The device is not really a rocket.

About memory usage: I know about this being an issue on devices with only 64MB memory. But not specially introduced by this pull request. Feel free to open another issue about this topic.

**Comment by metalstrolch** [comment]
OK. Going to merge this.
I think for devices like this it would be best idea to process a map throwing out everything one doesn't want to render anyway. While being done quite easy with maptool, we don't have an infrastructure to provide such maps yet. Additionally we could provide a map with all the rest. So one could have two binfiles. One for the roads and routing things. And another for the eyecandy like landuses and so forth. Then we could enable or disable that via the maps menu. Or opt not to have the second one at all. Maybe I'll give that aproach a try. Stay tuned.

**Pull request merged**
