### PR TITLE
[On_HOLD] fix:build:Fix an issue with buildroot unable to find libfib in its rpath

### PR DESCRIPTION
**Pull request by aerostitch**
Closes: #629
This is a patch from @naggety, see mentionned issue.
Needs to be tested, but I want to verify that it doesn't break any of our builds first.

### CODE REVIEW

**Comment by pgrandin** [comment]
While the patch might fix the issue for the OP, I am wondering if the root cause isn't somewhere else. I've used buildroot extensively myself  ( https://github.com/pgrandin/navit-buildroot/tree/master/packages/navit ) and haven't faced that issue. I need to dig into the OP's package code. We might want to wait before merging that.

**Comment by jkoan** [comment]
The difference between your two implementations are that @pgrandin set the LIB-DIR but @naggety didn't set it.

**Comment by metalstrolch** [comment]
There seems to be something else strange as well around fib.

On buildroot setup i try to build navit against qt5, but without plugin support. Still libfib gets built seperately. (I get libfib.so)
Doesn't happen on my Gentoo-PC and obviously not on sailfish MER build environment. Because there is no libfib.so then.

What's different on building fib?

**Comment by metalstrolch** [comment]
OK, found the libfib oddity with buildroot:
libfib is added to the project by simple "add_library" cmake function without explicitly stating how to link it. So the default behaviour of CMAKE in this case depends on the presence of the BUILD_SHARED_LIBS variable.

Buildroot sets BUILD_SHARED_LIBS environment on cmake to "ON". If unset (like on sailfish or my PC) the behaviour defaults to "NO".

For buildroot this can be fixed by explicitly stating BUILD_SHARED_LIBS in cmake run.
**But I suggest to alter supportlib_add_library macro to honour "USE_PLUGINS" setting as well.**

Or does anyone have better ideas?

**Comment by jkoan** [comment]
Please continue the dicussion within #629

**Pull request closed without merging**
