### PR TITLE
Add auto zoom toggle

### PR DESCRIPTION
**Pull request by jfitie**
https://github.com/navit-gps/navit/pull/225

### CODE REVIEW

**Comment by pgrandin** [comment]
I like the simplicity of this solution, but we probably need a different icon

**Comment by jfitie** [comment]
@pgrandin; suggestion: [gui_zoom.zip](https://github.com/navit-gps/navit/files/974210/gui_zoom.zip)

**Comment by pgrandin** [comment]
Perfect! can you please add them to the PR?

**Comment by jfitie** [comment]
Already removed the branch, hope this works. https://github.com/navit-gps/navit/pull/237/

**Comment by metalstrolch** [comment]
Closing this, as already merged with #237

**Pull request closed without merging**
