### PR TITLE
[Android] Enable autozoom by default

### PR DESCRIPTION
**Pull request by jfitie**
Enable autozoom by default so that car navigation automatically zooms in on the vehicle based on current speed. Very useful when navigating.

### CODE REVIEW

**Comment by pgrandin** [comment]
It works for me. @jandegr any opinion on this?

**Comment by jfitie** [comment]
Thanks for considering. Enabling this option by default gives the end user a much better out-of-box experience.

**Comment by jandegr** [comment]
Without some way to change it this discussion is just a matter of taste.
With smth. like below it can be made a user setting, leaving what the default
value should be open for further discussion.

> 

case R.id.toggle_autozoom:
				msg = Message.obtain(N_NavitGraphics.callback_handler, NavitGraphics.msg_type.CLB_CALL_CMD.ordinal());
				b = new Bundle();
				b.putString("cmd", "autozoom_active=autozoom_active==0?1:0");
				msg.setData(b);
				msg.sendToTarget();
				break;

**Comment by jfitie** [comment]
https://github.com/navit-gps/navit/pull/231/files

**Pull request merged**
