### PR TITLE
add:vehicle:vehicle_geoclue:Add Vehicle geoclue

### PR DESCRIPTION
**Pull request by jkoan**
This PR adds the new Geoclue vehicle.
Geoclue is a Position Libary which is available for at least Gnome based Desktops and also more importantly upcoming Linux Phones like the [PinePhone](https://wiki.pine64.org/index.php/PinePhone) or [Librem 5](https://en.wikipedia.org/wiki/Librem_5) include it as well (with `phosh` distro).

[Geoclue](https://gitlab.freedesktop.org/geoclue/geoclue/-/blob/master/README.md) also has an fallback to GeoIP or CellID (when supported) so the user should be presented with a location roughly in the neighborhood any time, even on PCs.
This is also important since i don't happen to have such a device around to test, but i have a PineTab which can be used for WiFi based location. In my around area we dont have much geotaged WiFis, but some, so i was able to see Navit jumping around. When the coverage would be better i really think this vehicle can be fluid.

Some things are not perfect however:
- geoclue needs an Internet connection for WiFi based location
- geoclue falls back to GeoIP when no WiFi based location could be found. In my case (because of my mobilephone hotspot) this was about 150km off. But with DSL (House internet) the GeoIP is much more accurate.
- In #1032 @Baggypants reported a crash, but i wasn't able to reproduce it at all

Tested:
- on x86 PC (AMD Ryzen with Manjaro Linux Gnome, Linux 5.8.16, geoclue 2.5.6 )
- PineTab

### CODE REVIEW

**Comment by fortysixandtwo** [comment]
Hey, I'm currently trying to build this on my pinephone (running mobian/debian).

And I'm having trouble generating the pngs with the `convert` provided by imagemagick-6q.16.
Since you tested this on the PineTab (which essentially runs the same software)
I was wondering which imagemagick you are using/how you got it to build on debian (see #1065)

**Comment by fortysixandtwo** [comment]
For the people who want to build this:
I had to rebase on the trunk in order to get the fixes for inkscape 1.0 usage (otherwise I would be calling inkscape with `--export-png`).

I guess I need to somehow configure the geoclue vehicle?
Because currently I'm getting no indication that navit has any location information.

Running `DISPLAY=:0 G_MESSAGES_DEBUG=all ~/install/bin/navit -d 3 2>&1 | tee navit.log` and then grepping for geoclue
I only get a single line:
```
50:info:navit:plugin_new:found plugin module file [19]: '/home/mobian/install/lib64/navit/vehicle/libvehicle_geoclue.so'
```

**Comment by fortysixandtwo** [comment]
Ok, I'm very happy to report that it actually works after adding
`<vehicle name="Geoclue" profilename="car" enabled="yes" source="geoclue://" active="1"/>`
to my configuration!

**Comment by jkoan** [comment]
> For the people who want to build this:
> I had to rebase on the trunk in order to get the fixes for inkscape 1.0 usage (otherwise I would be calling inkscape with `--export-png`).
> 
> I guess I need to somehow configure the geoclue vehicle?
> Because currently I'm getting no indication that navit has any location information.
> 
> Running `DISPLAY=:0 G_MESSAGES_DEBUG=all ~/install/bin/navit -d 3 2>&1 | tee navit.log` and then grepping for geoclue
> I only get a single line:
> 
> ```
> 50:info:navit:plugin_new:found plugin module file [19]: '/home/mobian/install/lib64/navit/vehicle/libvehicle_geoclue.so'
> ```

yes, sorry, i forgot to rebase before uploading. For a full config look into the issue #1032, i uploaded my config there

**Comment by fortysixandtwo** [comment]
Last time I tried, my position was not actually updating (and the first time I was stationary).
Will test again soon and report my findings.

**Pull request merged**
