### PR TITLE
Fix:wince:Remove useless files from the output

### PR DESCRIPTION
**Pull request by pgrandin**
Removed useless .cmake files from the generated artefacts

Files in the .zip now :
```
  adding: locale/ (stored 0%)
  adding: locale/eo/ (stored 0%)
  adding: locale/eo/LC_MESSAGES/ (stored 0%)
  adding: locale/eo/LC_MESSAGES/navit.mo (deflated 53%)
  adding: locale/bg/ (stored 0%)
  adding: locale/bg/LC_MESSAGES/ (stored 0%)
  adding: locale/bg/LC_MESSAGES/navit.mo (deflated 56%)
  adding: locale/nb/ (stored 0%)
  adding: locale/nb/LC_MESSAGES/ (stored 0%)
  adding: locale/nb/LC_MESSAGES/navit.mo (deflated 55%)
  adding: locale/sk/ (stored 0%)
  adding: locale/sk/LC_MESSAGES/ (stored 0%)
  adding: locale/sk/LC_MESSAGES/navit.mo (deflated 54%)
  adding: locale/sl/ (stored 0%)
  adding: locale/sl/LC_MESSAGES/ (stored 0%)
  adding: locale/sl/LC_MESSAGES/navit.mo (deflated 54%)
  adding: locale/kn/ (stored 0%)
  adding: locale/kn/LC_MESSAGES/ (stored 0%)
  adding: locale/kn/LC_MESSAGES/navit.mo (deflated 27%)
  adding: locale/el/ (stored 0%)
  adding: locale/el/LC_MESSAGES/ (stored 0%)
  adding: locale/el/LC_MESSAGES/navit.mo (deflated 56%)
  adding: locale/ta/ (stored 0%)
  adding: locale/ta/LC_MESSAGES/ (stored 0%)
  adding: locale/ta/LC_MESSAGES/navit.mo (deflated 58%)
  adding: locale/be/ (stored 0%)
  adding: locale/be/LC_MESSAGES/ (stored 0%)
  adding: locale/be/LC_MESSAGES/navit.mo (deflated 55%)
  adding: locale/lb/ (stored 0%)
  adding: locale/lb/LC_MESSAGES/ (stored 0%)
  adding: locale/lb/LC_MESSAGES/navit.mo (deflated 52%)
  adding: locale/ja/ (stored 0%)
  adding: locale/ja/LC_MESSAGES/ (stored 0%)
  adding: locale/ja/LC_MESSAGES/navit.mo (deflated 53%)
  adding: locale/nl/ (stored 0%)
  adding: locale/nl/LC_MESSAGES/ (stored 0%)
  adding: locale/nl/LC_MESSAGES/navit.mo (deflated 56%)
  adding: locale/cs/ (stored 0%)
  adding: locale/cs/LC_MESSAGES/ (stored 0%)
  adding: locale/cs/LC_MESSAGES/navit.mo (deflated 54%)
  adding: locale/ml/ (stored 0%)
  adding: locale/ml/LC_MESSAGES/ (stored 0%)
  adding: locale/ml/LC_MESSAGES/navit.mo (deflated 66%)
  adding: locale/lv/ (stored 0%)
  adding: locale/lv/LC_MESSAGES/ (stored 0%)
  adding: locale/lv/LC_MESSAGES/navit.mo (deflated 54%)
  adding: locale/th/ (stored 0%)
  adding: locale/th/LC_MESSAGES/ (stored 0%)
  adding: locale/th/LC_MESSAGES/navit.mo (deflated 60%)
  adding: locale/nn/ (stored 0%)
  adding: locale/nn/LC_MESSAGES/ (stored 0%)
  adding: locale/nn/LC_MESSAGES/navit.mo (deflated 55%)
  adding: locale/fy/ (stored 0%)
  adding: locale/fy/LC_MESSAGES/ (stored 0%)
  adding: locale/fy/LC_MESSAGES/navit.mo (deflated 33%)
  adding: locale/da/ (stored 0%)
  adding: locale/da/LC_MESSAGES/ (stored 0%)
  adding: locale/da/LC_MESSAGES/navit.mo (deflated 55%)
  adding: locale/fa/ (stored 0%)
  adding: locale/fa/LC_MESSAGES/ (stored 0%)
  adding: locale/fa/LC_MESSAGES/navit.mo (deflated 50%)
  adding: locale/cy/ (stored 0%)
  adding: locale/cy/LC_MESSAGES/ (stored 0%)
  adding: locale/cy/LC_MESSAGES/navit.mo (deflated 40%)
  adding: locale/es/ (stored 0%)
  adding: locale/es/LC_MESSAGES/ (stored 0%)
  adding: locale/es/LC_MESSAGES/navit.mo (deflated 56%)
  adding: locale/sc/ (stored 0%)
  adding: locale/sc/LC_MESSAGES/ (stored 0%)
  adding: locale/sc/LC_MESSAGES/navit.mo (deflated 53%)
  adding: locale/et/ (stored 0%)
  adding: locale/et/LC_MESSAGES/ (stored 0%)
  adding: locale/et/LC_MESSAGES/navit.mo (deflated 55%)
  adding: locale/ur/ (stored 0%)
  adding: locale/ur/LC_MESSAGES/ (stored 0%)
  adding: locale/ur/LC_MESSAGES/navit.mo (deflated 55%)
  adding: locale/vi/ (stored 0%)
  adding: locale/vi/LC_MESSAGES/ (stored 0%)
  adding: locale/vi/LC_MESSAGES/navit.mo (deflated 57%)
  adding: locale/ro/ (stored 0%)
  adding: locale/ro/LC_MESSAGES/ (stored 0%)
  adding: locale/ro/LC_MESSAGES/navit.mo (deflated 55%)
  adding: locale/pt/ (stored 0%)
  adding: locale/pt/LC_MESSAGES/ (stored 0%)
  adding: locale/pt/LC_MESSAGES/navit.mo (deflated 55%)
  adding: locale/lt/ (stored 0%)
  adding: locale/lt/LC_MESSAGES/ (stored 0%)
  adding: locale/lt/LC_MESSAGES/navit.mo (deflated 54%)
  adding: locale/fo/ (stored 0%)
  adding: locale/fo/LC_MESSAGES/ (stored 0%)
  adding: locale/fo/LC_MESSAGES/navit.mo (deflated 54%)
  adding: locale/jv/ (stored 0%)
  adding: locale/jv/LC_MESSAGES/ (stored 0%)
  adding: locale/jv/LC_MESSAGES/navit.mo (deflated 53%)
  adding: locale/de/ (stored 0%)
  adding: locale/de/LC_MESSAGES/ (stored 0%)
  adding: locale/de/LC_MESSAGES/navit.mo (deflated 56%)
  adding: locale/hu/ (stored 0%)
  adding: locale/hu/LC_MESSAGES/ (stored 0%)
  adding: locale/hu/LC_MESSAGES/navit.mo (deflated 55%)
  adding: locale/si/ (stored 0%)
  adding: locale/si/LC_MESSAGES/ (stored 0%)
  adding: locale/si/LC_MESSAGES/navit.mo (deflated 62%)
  adding: locale/gl/ (stored 0%)
  adding: locale/gl/LC_MESSAGES/ (stored 0%)
  adding: locale/gl/LC_MESSAGES/navit.mo (deflated 54%)
  adding: locale/mn/ (stored 0%)
  adding: locale/mn/LC_MESSAGES/ (stored 0%)
  adding: locale/mn/LC_MESSAGES/navit.mo (deflated 36%)
  adding: locale/de_CH/ (stored 0%)
  adding: locale/de_CH/LC_MESSAGES/ (stored 0%)
  adding: locale/de_CH/LC_MESSAGES/navit.mo (deflated 29%)
  adding: locale/af/ (stored 0%)
  adding: locale/af/LC_MESSAGES/ (stored 0%)
  adding: locale/af/LC_MESSAGES/navit.mo (deflated 54%)
  adding: locale/tr/ (stored 0%)
  adding: locale/tr/LC_MESSAGES/ (stored 0%)
  adding: locale/tr/LC_MESSAGES/navit.mo (deflated 54%)
  adding: locale/te/ (stored 0%)
  adding: locale/te/LC_MESSAGES/ (stored 0%)
  adding: locale/te/LC_MESSAGES/navit.mo (deflated 57%)
  adding: locale/it/ (stored 0%)
  adding: locale/it/LC_MESSAGES/ (stored 0%)
  adding: locale/it/LC_MESSAGES/navit.mo (deflated 56%)
  adding: locale/mk/ (stored 0%)
  adding: locale/mk/LC_MESSAGES/ (stored 0%)
  adding: locale/mk/LC_MESSAGES/navit.mo (deflated 57%)
  adding: locale/uk/ (stored 0%)
  adding: locale/uk/LC_MESSAGES/ (stored 0%)
  adding: locale/uk/LC_MESSAGES/navit.mo (deflated 57%)
  adding: locale/sr/ (stored 0%)
  adding: locale/sr/LC_MESSAGES/ (stored 0%)
  adding: locale/sr/LC_MESSAGES/navit.mo (deflated 58%)
  adding: locale/ckb/ (stored 0%)
  adding: locale/ckb/LC_MESSAGES/ (stored 0%)
  adding: locale/ckb/LC_MESSAGES/navit.mo (deflated 28%)
  adding: locale/zh_CN/ (stored 0%)
  adding: locale/zh_CN/LC_MESSAGES/ (stored 0%)
  adding: locale/zh_CN/LC_MESSAGES/navit.mo (deflated 50%)
  adding: locale/sw/ (stored 0%)
  adding: locale/sw/LC_MESSAGES/ (stored 0%)
  adding: locale/sw/LC_MESSAGES/navit.mo (deflated 53%)
  adding: locale/pms/ (stored 0%)
  adding: locale/pms/LC_MESSAGES/ (stored 0%)
  adding: locale/pms/LC_MESSAGES/navit.mo (deflated 45%)
  adding: locale/ko/ (stored 0%)
  adding: locale/ko/LC_MESSAGES/ (stored 0%)
  adding: locale/ko/LC_MESSAGES/navit.mo (deflated 51%)
  adding: locale/fr_CH/ (stored 0%)
  adding: locale/fr_CH/LC_MESSAGES/ (stored 0%)
  adding: locale/fr_CH/LC_MESSAGES/navit.mo (deflated 55%)
  adding: locale/id/ (stored 0%)
  adding: locale/id/LC_MESSAGES/ (stored 0%)
  adding: locale/id/LC_MESSAGES/navit.mo (deflated 55%)
  adding: locale/fi/ (stored 0%)
  adding: locale/fi/LC_MESSAGES/ (stored 0%)
  adding: locale/fi/LC_MESSAGES/navit.mo (deflated 55%)
  adding: locale/en_CA/ (stored 0%)
  adding: locale/en_CA/LC_MESSAGES/ (stored 0%)
  adding: locale/en_CA/LC_MESSAGES/navit.mo (deflated 64%)
  adding: locale/nds/ (stored 0%)
  adding: locale/nds/LC_MESSAGES/ (stored 0%)
  adding: locale/nds/LC_MESSAGES/navit.mo (deflated 55%)
  adding: locale/hr/ (stored 0%)
  adding: locale/hr/LC_MESSAGES/ (stored 0%)
  adding: locale/hr/LC_MESSAGES/navit.mo (deflated 53%)
  adding: locale/eu/ (stored 0%)
  adding: locale/eu/LC_MESSAGES/ (stored 0%)
  adding: locale/eu/LC_MESSAGES/navit.mo (deflated 55%)
  adding: locale/pt_BR/ (stored 0%)
  adding: locale/pt_BR/LC_MESSAGES/ (stored 0%)
  adding: locale/pt_BR/LC_MESSAGES/navit.mo (deflated 55%)
  adding: locale/en_AU/ (stored 0%)
  adding: locale/en_AU/LC_MESSAGES/ (stored 0%)
  adding: locale/en_AU/LC_MESSAGES/navit.mo (deflated 64%)
  adding: locale/sv/ (stored 0%)
  adding: locale/sv/LC_MESSAGES/ (stored 0%)
  adding: locale/sv/LC_MESSAGES/navit.mo (deflated 55%)
  adding: locale/ru/ (stored 0%)
  adding: locale/ru/LC_MESSAGES/ (stored 0%)
  adding: locale/ru/LC_MESSAGES/navit.mo (deflated 59%)
  adding: locale/en_GB/ (stored 0%)
  adding: locale/en_GB/LC_MESSAGES/ (stored 0%)
  adding: locale/en_GB/LC_MESSAGES/navit.mo (deflated 66%)
  adding: locale/zh_HK/ (stored 0%)
  adding: locale/zh_HK/LC_MESSAGES/ (stored 0%)
  adding: locale/zh_HK/LC_MESSAGES/navit.mo (deflated 50%)
  adding: locale/ca/ (stored 0%)
  adding: locale/ca/LC_MESSAGES/ (stored 0%)
  adding: locale/ca/LC_MESSAGES/navit.mo (deflated 55%)
  adding: locale/sq/ (stored 0%)
  adding: locale/sq/LC_MESSAGES/ (stored 0%)
  adding: locale/sq/LC_MESSAGES/navit.mo (deflated 56%)
  adding: locale/ku/ (stored 0%)
  adding: locale/ku/LC_MESSAGES/ (stored 0%)
  adding: locale/ku/LC_MESSAGES/navit.mo (deflated 33%)
  adding: locale/en/ (stored 0%)
  adding: locale/en/LC_MESSAGES/ (stored 0%)
  adding: locale/en/LC_MESSAGES/navit.mo (deflated 61%)
  adding: locale/ar/ (stored 0%)
  adding: locale/ar/LC_MESSAGES/ (stored 0%)
  adding: locale/ar/LC_MESSAGES/navit.mo (deflated 57%)
  adding: locale/hi/ (stored 0%)
  adding: locale/hi/LC_MESSAGES/ (stored 0%)
  adding: locale/hi/LC_MESSAGES/navit.mo (deflated 53%)
  adding: locale/fil/ (stored 0%)
  adding: locale/fil/LC_MESSAGES/ (stored 0%)
  adding: locale/fil/LC_MESSAGES/navit.mo (deflated 49%)
  adding: locale/bs/ (stored 0%)
  adding: locale/bs/LC_MESSAGES/ (stored 0%)
  adding: locale/bs/LC_MESSAGES/navit.mo (deflated 47%)
  adding: locale/fr/ (stored 0%)
  adding: locale/fr/LC_MESSAGES/ (stored 0%)
  adding: locale/fr/LC_MESSAGES/navit.mo (deflated 56%)
  adding: locale/ast/ (stored 0%)
  adding: locale/ast/LC_MESSAGES/ (stored 0%)
  adding: locale/ast/LC_MESSAGES/navit.mo (deflated 55%)
  adding: locale/kk/ (stored 0%)
  adding: locale/kk/LC_MESSAGES/ (stored 0%)
  adding: locale/kk/LC_MESSAGES/navit.mo (deflated 30%)
  adding: locale/zh_TW/ (stored 0%)
  adding: locale/zh_TW/LC_MESSAGES/ (stored 0%)
  adding: locale/zh_TW/LC_MESSAGES/navit.mo (deflated 53%)
  adding: locale/pl/ (stored 0%)
  adding: locale/pl/LC_MESSAGES/ (stored 0%)
  adding: locale/pl/LC_MESSAGES/navit.mo (deflated 54%)
  adding: locale/mr/ (stored 0%)
  adding: locale/mr/LC_MESSAGES/ (stored 0%)
  adding: locale/mr/LC_MESSAGES/navit.mo (deflated 56%)
  adding: locale/he/ (stored 0%)
  adding: locale/he/LC_MESSAGES/ (stored 0%)
  adding: locale/he/LC_MESSAGES/navit.mo (deflated 55%)
  adding: maps/ (stored 0%)
  adding: maps/osm_bbox_11.3,47.9,11.7,48.2.bin (deflated 1%)
  adding: maps/osm_bbox_11.3,47.9,11.7,48.2.xml (deflated 1%)
  adding: icons/ (stored 0%)
  adding: icons/nav_right_1_32.xpm (deflated 85%)
  adding: icons/nav_left_1.xpm (deflated 94%)
  adding: icons/nav_right_2.xpm (deflated 94%)
  adding: icons/restroom.xpm (deflated 56%)
  adding: icons/flag_bk_wh.xpm (deflated 78%)
  adding: icons/desktop_icons/ (stored 0%)
  adding: icons/desktop_icons/navit.desktop (deflated 41%)
  adding: icons/gui_sound_off_32.xpm (deflated 71%)
  adding: icons/highway_exit.xpm (deflated 55%)
  adding: icons/nav_right_2_32.xpm (deflated 85%)
  adding: icons/nav_left_2_32.xpm (deflated 85%)
  adding: icons/flag_bl_wh.xpm (deflated 78%)
  adding: icons/nav_left_2.xpm (deflated 94%)
  adding: icons/gc_reference.xpm (deflated 53%)
  adding: icons/cmake_install.cmake (deflated 81%)
  adding: icons/nav_left_1_32.xpm (deflated 85%)
  adding: icons/trailerpark.xpm (deflated 53%)
  adding: icons/gc_event.xpm (deflated 57%)
  adding: icons/gc_question.xpm (deflated 59%)
  adding: icons/gc_webcam.xpm (deflated 53%)
  adding: icons/dumping_station.xpm (deflated 57%)
  adding: icons/nav_straight_32.xpm (deflated 86%)
  adding: icons/gc_mystery.xpm (deflated 56%)
  adding: icons/flag_bk_tr.xpm (deflated 79%)
  adding: icons/Makefile (deflated 78%)
  adding: icons/bus_halt.xpm (deflated 58%)
  adding: icons/nav_straight.xpm (deflated 95%)
  adding: icons/gc_tradi.xpm (deflated 56%)
  adding: icons/nav_right_1.xpm (deflated 94%)
  adding: icons/gc_multi.xpm (deflated 57%)
  adding: icons/gui_sound_32.xpm (deflated 69%)
  adding: icons/gc_stages.xpm (deflated 55%)
  adding: icons/flag_wh_bk.xpm (deflated 78%)
  adding: navit.xml (deflated 89%)
  adding: navit.exe (deflated 63%)
```

We will need to add the svg/png icons at some point, but this is a separate issue.

### CODE REVIEW

**Comment by jkoan** [comment]
Maps should also not be included because it is always a very old one of Munich

**Comment by pgrandin** [comment]
Well the map one is tricky, because without maps users get a yellow empty screen.
Thoughts?

**Comment by jkoan** [comment]
That's true but it's also not the best to provide a really old map. So I would just like to provide no map or a fake map with in the Form of "Navit is working now get your real maps. See xyz for help. Happy driving" so the streets Form a text

**Comment by pgrandin** [comment]
That map is old indeed, but it's only here for demo purpose, as it only covers a very small area.
It is technically easy to provide a more up-to-date map if we want to : we just need to export the demo map say, weekly, and maybe push it to the download center.

Thoughts?

**Pull request merged**
