### PR TITLE
Add:gui_internal:Support native on-screen keyboard (currently Android only)

### PR DESCRIPTION
**Pull request by mvglasow**
Rebased as discussed with sleske, replaces #47

### CODE REVIEW

**Comment by pgrandin** [comment]
APK for tests : https://circle-artifacts.com/gh/mvglasow/navit/34/artifacts/0/tmp/circle-artifacts.xJXZDpY/navit-a28ea531c8a792751d8c3630ff7d1e19169ab2f8-debug.apk

**Comment by pgrandin** [comment]
How to enable the native keyboard isn't obvious to me. Michael, can you please help?

**Comment by mvglasow** [comment]
`<gui keyboard="false"/>`

The setting has been around for quite some time. Until now it just disabled Navit's own keyboard so that the system keyboard could be used in its place, but left it up to the platform and/or the user to actually bring up the keyboard. With my changes, it will now bring up the native keyboard on platforms that support it. See also http://trac.navit-project.org/ticket/712#comment:1.

@pgrandin Thanks for linking the APK, I'll do that from now on.

**Comment by pgrandin** [comment]
Thanks for the clarification. Maybe we should set this attribute in the related build to make testing easier?
I do not own the android device I am currently testing on, so it is not rooted, and editing the xml file isn't really user friendly.
Regarding the APK, maybe we can figure out a way to automatically link the artifacts when we have a PR open for a given branch using the CircleCI API, I'll have a look.

**Comment by mvglasow** [comment]
@pgrandin I've built an APK with the netive keyboard enabled, available at https://circle-artifacts.com/gh/mvglasow/navit/38/artifacts/0/tmp/circle-artifacts.mXrexhx/navit-6920eb6479966b2b7aafc383b8ba59147119e48b-debug.apk.

It's a branch of this branch which had only the XML attribute changed. For this merge request, I'm planning on leaving the configuration untouched. The keyboard is still somewhat experimental (and currently supported only on a single platform), therefore I'd like to keep it opt-in for the tech-savvy folks until we've had some testing. After that we can discuss about what the default should be.

**Comment by mvglasow** [comment]
Just a quick heads-up: rebased on current trunk yesterday and noticed some strange behavior (internal keyboard showing underneath native one). I'll investigate and report back.

**Comment by mvglasow** [comment]
Fixed it. As it turns out, greg's recent fixes to the internal keyboard and my additions were not compatible with each other – after adding some checks for the keyboard preference things work as originally intended. I also fixed another, unrelated bug which prevented hiding the native keyboard upon submitting a POI search.

APKs:
* As per this merge request, ARM: https://circle-artifacts.com/gh/mvglasow/navit/63/artifacts/0/tmp/circle-artifacts.g64yIIm/navit-3f9cc2b3e127d6f4d48de4b832bcb13059c637f2-debug.apk
*  Same for x86: https://circle-artifacts.com/gh/mvglasow/navit/63/artifacts/0/tmp/circle-artifacts.g64yIIm/navit-3f9cc2b3e127d6f4d48de4b832bcb13059c637f2-x86-debug.apk
* Native keyboard enabled by default (for those who can't edit their navit.xml file), ARM: https://circle-artifacts.com/gh/mvglasow/navit/64/artifacts/0/tmp/circle-artifacts.Ab0prdR/navit-3d2e76c32d2927eb4a3bcbbe794074878d16f1e4-debug.apk
* Same for x86: https://circle-artifacts.com/gh/mvglasow/navit/64/artifacts/0/tmp/circle-artifacts.Ab0prdR/navit-3d2e76c32d2927eb4a3bcbbe794074878d16f1e4-x86-debug.apk

**Comment by pgrandin** [comment]
@mvglasow would you mind updating the PR to fix the conflicts?

**Comment by mvglasow** [comment]
Done.

**Comment by mvglasow** [comment]
*grmbl* just tested and the internal keyboard's again showing underneath the platform keyboard. Bear with me, I'll have a look at why this is happening and report back.

**Comment by mvglasow** [comment]
Got it finally. Seems I'd forgotten to include the two commits that fixed the error.

APKs as per this merge request (`navit.xml` editing needed to use the new feature):
* ARM: https://circle-artifacts.com/gh/mvglasow/navit/88/artifacts/0/tmp/circle-artifacts.eCMdOJs/navit-53b333a617146bc304063f8ddd0dfe2927bb6064-debug.apk
* x86: https://circle-artifacts.com/gh/mvglasow/navit/88/artifacts/0/tmp/circle-artifacts.eCMdOJs/navit-53b333a617146bc304063f8ddd0dfe2927bb6064-x86-debug.apk

APKs with platform keyboard enabled by default:
* ARM: https://circle-artifacts.com/gh/mvglasow/navit/89/artifacts/0/tmp/circle-artifacts.znlNZW8/navit-561b62813bef25f7ab0ea19760b1021a1197dd08-debug.apk
* x86: https://circle-artifacts.com/gh/mvglasow/navit/89/artifacts/0/tmp/circle-artifacts.znlNZW8/navit-561b62813bef25f7ab0ea19760b1021a1197dd08-x86-debug.apk

**Pull request merged**
