### PR TITLE
Add RaspberryPI hardware accelerated graphics support

### PR DESCRIPTION
**Pull request by cedricp**
This is work in progress but functional. Still improving it.

### CODE REVIEW

**Comment by pgrandin** [comment]
Thanks @cedricp !

I would like to request a few changes:
- EGL could be used on other platforms than rasperry pi, so maybe we should name that driver egl instead of rpi? (this is of course open to discussion)
- we have always been bad at documenting the code, but we need to get better at it :) Could you please add a few doxygen comments ? https://github.com/navit-gps/navit/blob/trunk/navit/plugin/j1850/j1850.c is a decent example
- why do we need this?
```
SET(CMAKE_SHARED_LIBRARY_SONAME_C_FLAG "-Wl,-soname,/data/data/org.navitproject.navit/lib/")
```

Otherwise this is really nice to get hardware accelerated graphics support for the rpi, I am sure that many users will enjoy it (myself included ;) )

Thanks!

**Comment by ernesto75** [comment]
Il 22/feb/2017 11:51 AM, "Pierre GRANDIN" <notifications@github.com> ha
scritto:

Thanks @cedricp <https://github.com/cedricp> !

I would like to request a few changes:

   - EGL could be used on other platforms than rasperry pi, so maybe we
   should name that driver egl instead of rpi? (this is of course open to
   discussion)

If I remember correctly, there is also navit for maemo on Nokia N900 an ARM
based device using gles2

**Comment by cedricp** [comment]
Ok to rename it to 'egl'. I've just added polygon filling feature (much more pretty !).
I'm starting documenting the code. I'm facing a strange issue with the compass and next_turn OSD, it crashes the application, gdb doesn't tell me anything (no trace back) apart a stack corruption... Any ideas ? Others OSDs are working fine, though.

**Comment by jandegr** [comment]
AFAIK this reverts 7782ba30130fb0aadb6ffea1596b29560796fdf2, please NO

**Comment by pgrandin** [comment]
Thanks @jandegr 
So it looks like this is because @cedricp 's code is based on a trunk from over 23 days ago.

**Comment by cedricp** [comment]
Did a lot of fixes... 
* Polygon filling 
* Renamed rpi to egl
* Overlays are working, but still have an crash issue when in release mode, ok in debug (????)
* enabled drag_bitmap to improve reactivity

Hope you'll like it :)

**Comment by cedricp** [comment]
Overlay crash fixed, no more severe bug :)

**Comment by pgrandin** [comment]
Nice work, thanks @cedricp !
I'll look into adding some build tests for this driver.

**Comment by cedricp** [comment]
Thank you, for a Raspberry build, you may need to tweak cflags : 
cmake (...) -DCMAKE_C_FLAGS="-I[/path/to/videocore_devel]/include/interface/vcos/pthreads -I[/path/to/videocore_devel]/include/interface/vmcs_host/linux

**Comment by pgrandin** [comment]
@cedricp I just gave a quick shot at testing this on my pi running Raspbian, and I have a few questions.
Could you please clarify the dependencies? You mention sdl2 but iirc until now we were using sdl1.2

A few notes here or in the wiki about how to setup the dependencies includeing the vocs/vmcs part would be really helpful.

Also, did you try this using the framebuffer or only with X?

Thanks!

**Comment by cedricp** [comment]
Hi,
I needed to use SDL2 as it is the only one that supports EGL context. The application runs without a XServer and uses videocore dispmanx as rendering context.

There are a lot of doc that explain how to compile SDL2 on RPi, but basically, here is how I do : 
(I use a cross compiler on my side)
    **EXTRA_CFLAGS="-I$LIB_PREFIX/include/interface/vcos/pthreads -I$LIB_PREFIX/include/interface/vmcs_host/linux"
    EXTRA_CXXFLAGS="-I$LIB_PREFIX/include/interface/vcos/pthreads -I$LIB_PREFIX/include/interface/vmcs_host/linux"**

**configure \
            --disable-pulseaudio \
            --disable-esd \
            --disable-video-mir \
            --disable-video-wayland \
            --disable-video-x11 \
            --disable-video-opengl \
            --enable-static --enable-shared \
            CFLAGS="$EXTRA_CFLAGS" CXXFLAGS="$EXTRA_CXXFLAGS"**

The video driver should compile fine once correctly compiled.
Hope it helps

**Comment by cedricp** [comment]
Hi, I recently fixed some issues on this graphic driver here : https://github.com/cedricp/navit/tree/rpi/navit/graphics/egl
* No more glitches when dragging map
* Tested on a Rpi3, the rendering is really fast and responsive
* Added multisampling method (not as good as I expected, but working)
I'll post a video ASAP

**Comment by jkoan** [comment]
If you are finished please make a new Pull Request ;)

**Comment by cedricp** [comment]
OK, I'm currently adding an overlay plugin to show vehicle information from CAN bus and as soon as all is up and running, I'll make a new PR.
BTW, is it possible to give real vehicle speed to NavIt (from vehicle bus) to improve navigation (if GPS signal is lost, for example) ?

**Comment by cedricp** [comment]
I also made a **buildroot** config (with a lot of packages fix) to create a _NavIt_ **ISO** image for Raspberry Pi 3 with just needed libs and services (GPSD/freetype/SDL2/fontconfig, etc.)
https://gitlab.com/DrQuark/buildroot_rpi3
Contact me if you're interested.

**Pull request merged**
