### PR TITLE
Add:icon:height

### PR DESCRIPTION
**Pull request by youte62**
height-montage

### CODE REVIEW

**Comment by pgrandin** [comment]
Nice icon, but it looks more like a weight, not 'height' :)

**Comment by metalstrolch** [comment]
Technically OK for me, but this kind of "road sign" style is unusual outside of the US. Beside that, we have no framework to translate text on icons, have we?

**Comment by pgrandin** [comment]
You're right @metalstrolch icon should probably avoid using text as it won't be translated.
Also, I'm actually not sure if we really need this one.
OSM uses `maxheight=*` for bridge clearance. `height` is used for building heights, which we currently don't use in Navit : http://wiki.openstreetmap.org/wiki/Key:height

The only reference to the height icon I could find in Navit was in the Garmin types : https://github.com/navit-gps/navit/blob/trunk/navit/map/garmin/garmintypes.txt#L205-L206

Reading that file I am unsure of its usage.

**Comment by pgrandin** [comment]
Too long without updates, closing the PR.

**Pull request closed without merging**
