### PR TITLE
Add:graphics/sdl: Polygon with holes support.

### PR DESCRIPTION
**Pull request by metalstrolch**
Add polygon with holes support to SDL graphics.

### CODE REVIEW

**Comment by metalstrolch** [comment]
@jkoan: you can retest multi polygon support with SDL. I added the support for it.

**Comment by metalstrolch** [comment]
Can somebody check this on tomtom as well? Seems tomtom uses sdl.

**Comment by gefin** [comment]
Yes, i can test tomtom.. 
Is there a source to download a matching map ( ~300-800 MB )

**Comment by metalstrolch** [comment]
I've created one: http://metalstrolche.de/bayern.bin
Covers Bavaria / Germany. Sample map Munich is contained within it.
I will edit this post when I take it down again.

**Comment by metalstrolch** [comment]
You may want to try the map contained there as well. Center Navit to Munich before loading this map. You should see some shapes. Some of them should have holes.
[fake-munich.zip](https://github.com/navit-gps/navit/files/3580005/fake-munich.zip)

**Comment by gefin** [comment]
Real map look good. Multi polygons are drawn.
The Fake-Munich stay blank.
Is there a debug line to grep for?

**Comment by metalstrolch** [comment]
Yes the size is OK, there are only few polygon shapes inside. That's no "real" map.
Of course you can check if the map got loaded at all. But I think you just miss the not that big elements.
They are roughly at 48.1333N 11.5666E. You can enter these coordinates in Actions->Coordinates in internal GUI.

**Comment by gefin** [comment]
All blank. Map are loaded. May be my Layout don't show this type of object.
Are also normal objects on the map?

**Comment by metalstrolch** [comment]
The objects are all of type poly_landfill. You can enable them by adding
```
      <itemgra item_types="poly_landfill" order="10-">
         <polygon color="#999893"/>
         <text text_size="5"/>
      </itemgra>
```
To your layout. There are no other objects inside the fake map. Maybe I do one with some POIs and different landuse tags tomorrow.

**Comment by metalstrolch** [comment]
If you have an old version without this patch, you still will see the polygons, but the holes are filled as well.

**Comment by gefin** [comment]
Yes with the "landfill" i see a polygon (6 corner) with a hole (3 corner) and a square with a hole  and a polygon in this hole.
look like it work ;-)

**Comment by metalstrolch** [comment]
Seems we're ready to go.

**Comment by gefin** [comment]
After driving ~100km with this version on tomtom 730 i found a location where the performance drop strong. Time for one screen update is then up to 4 sec. Things like unexpected "turn if possible" happens.
The problem exist only with car layout. Car-simple layout 0.3 sec is good. 

Location is 48°8'24'' N    12°1`50`` E  along the B12
zoom=32
I dont see a problematic object at this location.

**Comment by metalstrolch** [comment]
No, it's not because of replacing draw_polygon() by draw_polygon_with_holes() as this works exactly the same as before if something doesn't have holes. The new version should be even faster than before as the coordinates are memcopied one time less.

It's missing clipping for polygons with holes I think, together with the sheer size of some polygons.

Seems this happens because of two really large polygons with many holes having a quite high node count each:
https://www.openstreetmap.org/relation/2892951
and
https://www.openstreetmap.org/relation/68363
At the location 48°8'24'' N 12°1`50`` E along the B12.

Currently core doesn't implement clipping for polygons with holes. It does for polygons without holes.
And the WindowsCE (and SDL) graphics do not implement clipping as well.
So the polygons are completely raycasted and drawn even if only small portions of them are really on screen.

I'll try two things:
1. Port the "clipping" version of polygon handling in graphics.c to support holes as well. I've left a TODO there anyways.

2. Check  layer geometry on Windows / SDL graphics to only raycast lines which are actually on layer.

Opened #869 as this pull request is already closed.

**Pull request merged**
