### PR TITLE
Zip code search only

### PR DESCRIPTION
**Pull request by OLFDB**

### CODE REVIEW

**Comment by jkoan** [comment]
Whats the current state of this PR? Can it be closed, or is there still ongoing work?

**Comment by lains** [comment]
Hello @OLFDB, what is the intent of this PR?
It seems it adds an internal GUI command to search by zipcode. Is this right?
There are also other changes mixed inside this PR:
* changes on traffic (module traffic/traff_file)
  Is this intentional. @mvglasow, should this code be part of another PR, is it already part of another PR
* indentation and style changes
  Are these needed? Shouldn't they be split out into another separate PR?

**Comment by OLFDB** [comment]
The intent of the CR is to add search by zipcode. 
The traffic changes are not related to this PR. 
Can you support in moving them on a seperate branch?

**Comment by jkoan** [comment]
Only https://github.com/navit-gps/navit/pull/770/commits/10eab7f1a7b4885a8c4349880a64dcd16ed06eff seems contain the changes that sould be in this change, is that true?

**Comment by hoehnp** [comment]
@OLFDB: Thanks a lot for this idea. Recently when travelling i facing the issue that many cities might have the same name, so it is difficult to find from the search which one is the right city. I think searching for zip code would already resolve this.

**Comment by aerostitch** [comment]
Is this still relevant after @metalstrolch 's changes from https://github.com/navit-gps/navit/pull/818 ?

**Comment by jkoan** [comment]
As this is only a Draft and probably also invalid i will close this now. Feel free to open new PRs at any time

**Pull request closed without merging**
