### PR TITLE
Removing autotools support

### PR DESCRIPTION
**Pull request by pgrandin**
As per http://trac.navit-project.org/ticket/1341 we are removing autotools support. 
I'm opening this PR for a collective review to ensure I did not miss something.

### CODE REVIEW

**Comment by mvglasow** [comment]
You might want to go through the XSLT files in the xslt folder – autotools and cmake use different sets of files, thus dropping autotools will render some XSLT files obsolete.

**Comment by ernesto75** [comment]
Without autotools, no more Navit for maemo5/N900 ? See
https://talk.maemo.org/showthread.php?t=38800&page=72
Il 31/dic/2015 11:16, "Pierre GRANDIN" <notifications@github.com> ha
scritto:

**Comment by mdankov** [comment]
We are not going to drop support of any platform with active users of navit.

It looks like maemo cmake build problem is related only to png conversion stage, see http://talk.maemo.org/showpost.php?p=1277788&postcount=631
I think we can make that conversion go exactly the same way as it goes in autotools build. Actually we support a few conversion programs, but they maybe have slightly different options passed during autotools build. Also, these programs may be tried in different orders with autotools and cmake.

To fix the issue, we'll need build logs of a successful build with autotools and a broken cmake build in the same environment, and scripts used to configure the build. 

I think the proper place to discuss it would be a separate ticket on trac.navit-project.org.

**Comment by sleske** [comment]
Kudos for finally going through with this! Maintaining two build systems in parallel just does not make sense in the longer run.
As to Maemo: It's unlikely there is any fundamental problem with the Maemo build and CMake, I'm confident we'll find a solution (or at least a hack, if needs be). At any rate, that's no reason to keep autotools.

**Comment by ernesto75** [comment]
I'm not a developer but one of the Navit users on the maemo platform.
Months ago i put these building scripts written by the guy who used to
build Navit for maemo here
https://github.com/navit-gps/navit/tree/ernesto75/build-scripts. He managed
to build it with autotools but not with cmake. I hope someone can find a
workaround for cmake

**Comment by sleske** [comment]
@ernesto75: I personally cannot fix the Maemo build, as I do not have the build environment set up. However, if someone tries building for Maemo with CMake and runs into problems, I'll be glad to help. In that case, it's best to open a bug on http://trac.navit-project.org/ describing the problem.

**Comment by pgrandin** [comment]
@sleske actually you can see the compilation output here : https://circleci.com/gh/navit-gps/navit/122 
Ideally we will probably want to build also via CircleCI. As @ernesto75 said an effort was started some time ago in that specific branch ( that maybe we should rename "maemo" ).
The current issue is not directly related to cmake though.

**Comment by ernesto75** [comment]
I agree. The current issue seems related to wrong scratchbox
installation/configuration.not cmake. I can suggest to try a scratchbox
virtual image with sdk preinstalled

http://maemo.muarf.org/tablets-dev/maemo_dev_env_downloads/

File: maemo ubuntu lucid desktop sdk virtual image final.7z

And try to build with cmake
Il 07/gen/2016 08:55, "Pierre GRANDIN" <notifications@github.com> ha
scritto:

**Comment by mdankov** [comment]
Ernesto75, we seem to miss 'debian' directory from https://github.com/navit-gps/navit/tree/ernesto75 . It should contain important files needed for compilation. For example, there expected to be 'rules' file which probably contains the actual compile script. Can you share your 'debian' directory?

**Comment by ernesto75** [comment]
This is the dropbox link to the debian directory used for maemo 
https://www.dropbox.com/sh/x3z8sus6rz9neja/AABHco6wPqBNPh7OPxLki4kwa?dl=0

Il 07/01/2016 20:30, mdankov ha scritto:

**Comment by mdankov** [comment]
ernesto75, thank you!
I'm going to give it a try today. 

But it looks like it's autotools build scripts. Do you have a copy of debian directory which results in failed build attempt on navit-data package, like it was described in posts you gave us links to.

**Comment by ernesto75** [comment]
No. I just know they tried but not working for many reasons. Quoting:
1. For a long time, building with cmake produced many errors, thats why it
was preferred to build with autotools
2. It still produces many errors mainly because cmake is searching for
headers in different directories.
3. dpkg-buildpackage scripts inside 'debian' folder use autotools and
compiles the source code with it. Today I workaround-ed that with the
following commands
Code:
cmake /path/to/sources
make
dpkg-buildpackage -b -nc
i had to specify -nc because dpkg will 'make clean' and will compile with
autotools again. So anybody who is expert at making "debian" dirs is
welcomed to help us switch to cmake entirely
Il 08/gen/2016 13:05, "mdankov" <notifications@github.com> ha scritto:

**Comment by sleske** [comment]
ernesto75:
> dpkg-buildpackage scripts inside 'debian' folder use autotools and compiles the source code with it. 
> Today I workaround-ed that with the following commands

That should not be necessary. The Debian tools do have support for CMake, not just for autotools. Actually, the official Debian package ( https://packages.debian.org/sid/navit  ) was converted to use CMake recently. That can hopefully serve as an example.

**Comment by mdankov** [comment]
I've got a few errors building in the ubuntu image, most of them are related to the image being quite old. I was able to resolve all of them by running 'apt-get update' and 'apt-get install' for some selected packages, most notable ones are autotools and libtool. Though maybe 'apt-get upgrade' would be more correct.

I had to install a few packages as well to fulfil  dependencies, as reported by dpkg-buildpackage. Though I'm unsure if espeak is actually needed during build.

During the build, I've got a error about missing libfreetype6-navit-dev package, which is marked as required for the build. I'm running now the build with libfreetype6-dev, with the -d key passed to dpkg-buildpackage. Is there some known problem with system-supplied libfreetype? Where then can I get the proper (patched?) one?

No fatal errors so far, but the build in qemu goes to take a while...

**Comment by mdankov** [comment]
ok, build has finished, but it actually was an i386 build.

I forgot to issue sb-conf select FREMANTLE_ARMEL beforehand.

And it looks like I can't install any dependencies after that command. 

```
bash-3.00$ sb-conf select FREMANTLE_X86
bash-3.00$ apt-get install libespeak-dev
Reading package lists... Done
Building dependency tree... Done
libespeak-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 15 not upgraded.
bash-3.00$ sb-conf select FREMANTLE_ARMEL
bash-3.00$ apt-get install libespeak-dev
Reading package lists... Done
Building dependency tree... Done
E: Couldn't find package libespeak-dev
bash-3.00$ apt-get update
Ign http://repository.maemo.org fremantle/sdk Release.gpg
Ign http://repository.maemo.org fremantle/tools Release.gpg
Ign http://repository.maemo.org fremantle/4bc37c7c77ebe90177c050b805a8dc79 Release.gpg
Ign http://repository.maemo.org fremantle/sdk Release
Ign http://repository.maemo.org fremantle/tools Release
Ign http://repository.maemo.org fremantle/4bc37c7c77ebe90177c050b805a8dc79 Release
Ign http://repository.maemo.org fremantle/sdk/free Packages/DiffIndex
Ign http://repository.maemo.org fremantle/sdk/non-free Packages/DiffIndex
Ign http://repository.maemo.org fremantle/sdk/free Sources/DiffIndex
Ign http://repository.maemo.org fremantle/tools/free Packages/DiffIndex
Ign http://repository.maemo.org fremantle/tools/non-free Packages/DiffIndex
Ign http://repository.maemo.org fremantle/tools/free Sources/DiffIndex
Ign http://repository.maemo.org fremantle/4bc37c7c77ebe90177c050b805a8dc79/nokia-binaries Packages/DiffIndex
Hit http://repository.maemo.org fremantle/sdk/free Packages
Hit http://repository.maemo.org fremantle/sdk/non-free Packages
Hit http://repository.maemo.org fremantle/sdk/free Sources
Hit http://repository.maemo.org fremantle/tools/free Packages
Hit http://repository.maemo.org fremantle/tools/non-free Packages
Hit http://repository.maemo.org fremantle/tools/free Sources
Hit http://repository.maemo.org fremantle/4bc37c7c77ebe90177c050b805a8dc79/nokia-binaries Packages
Reading package lists... Done
bash-3.00$ apt-get install libespeak-dev
Reading package lists... Done
Building dependency tree... Done
E: Couldn't find package libespeak-dev
bash-3.00$ 
```
Any ideas?

**Comment by ernesto75** [comment]
I remember some system related  issue about freetype. You can find patched
freetype here http://bokomoko.de/~rd/maemo/unstable/

for details read
https://talk.maemo.org/showpost.php?p=1017888&postcount=508

**Comment by ernesto75** [comment]
For the installation of espeak i don't know. Should be there
http://maemo.org/packages/package_instance/view/fremantle_extras-testing_free_armel/libespeak-dev/1.46.27/

**Comment by mdankov** [comment]
I have added following lines to the /etc/apt/sources.lst while in FREMANTLE_ARMEL mode:
```
deb http://repository.maemo.org/extras/ fremantle free non-free
deb http://repository.maemo.org/extras-testing/ fremantle free non-free
deb http://repository.maemo.org/extras-devel/ fremantle free non-free
```
Now  'apt-get install libdevil-dev libespeak-dev libimlib2-dev libfribidi-dev libpq-dev librsvg2-bin' doesn't complain on inability to find packages, but it does on lots of unresolved dependencies in the system. It suggests to run apt-get -f install, but it fails too.

Attempted to install deb file manually:
```
bash-3.00$ sb-conf select FREMANTLE_ARMEL
bash-3.00$ dpkg -i ../deps/libdevil-dev_1.7.5-5maemo1_armel.deb 
dpkg: error processing ../deps/libdevil-dev_1.7.5-5maemo1_armel.deb (--install):
 package architecture (armel) does not match system (i386)
Errors were encountered while processing:
 ../deps/libdevil-dev_1.7.5-5maemo1_armel.deb
```
Looks like i'm missing something...

**Comment by mdankov** [comment]
It appears the following lines being added to /etc/apt/sources.list, break the dpkg system of scratchbox. 
```
deb http://repository.maemo.org/extras/ fremantle free non-free
deb http://repository.maemo.org/extras-testing/ fremantle free non-free
deb http://repository.maemo.org/extras-devel/ fremantle free non-free
```
Am I expected to download deb's to satisfy build dependencies and install them with dpkg? Or is there some other way?

**Comment by ernesto75** [comment]
Maybe try this:
Copy the sources.list entry given to you after the license acceptance to
your Scratchbox x86 and armel target’s /etc/apt/sources.list file.

EDIT: You can now just use the following sources.list entry:

deb http://repository.maemo.org/ fremantle/4bc37c7c77ebe90177c050b805a8dc79
nokia-binaries
Execute the commands below on the FREMANTLE_ARMEL and FREMANTLE_X86 targets.

[sbox-FREMANTLE_X86: ~] > sb-conf select FREMANTLE_ARMEL
[sbox-FREMANTLE_ARMEL: ~] > nano /etc/apt/sources.list  # add deb line
[sbox-FREMANTLE_ARMEL: ~] > apt-get update
[sbox-FREMANTLE_ARMEL: ~] > fakeroot apt-get install nokia-binaries
nokia-apps
[sbox-FREMANTLE_ARMEL: ~] > sb-conf select FREMANTLE_X86
[sbox-FREMANTLE_X86: ~] > nano /etc/apt/sources.list  # add deb line
[sbox-FREMANTLE_X86: ~] > apt-get update
[sbox-FREMANTLE_X86: ~] > fakeroot apt-get install nokia-binaries nokia-apps
The above step installs all needed Nokia proprietary binary packages along
with the open source binaries that have dependencies to Nokia proprietary
binary packages. With this, your Maemo 5 SDK environment is set up
completely and ready for development.

13. If you got any DNS errors with apt-get install resolving '
repository.maemo.org', you have need to update the resolver config inside
scratchbox with sudo /scratchbox/sbin/sbox_sync

**Comment by mdankov** [comment]
Hi!

People on maemo irc channel suggested following sources.list:
```
deb http://repository.maemo.org/ fremantle/sdk free non-free
deb-src http://repository.maemo.org/ fremantle/sdk free
deb http://repository.maemo.org/ fremantle/tools free non-free
deb-src http://repository.maemo.org/ fremantle/tools free
deb http://repository.maemo.org fremantle/4bc37c7c77ebe90177c050b805a8dc79 nokia
deb-src http://repository.maemo.org/extras/ fremantle-1.3 free
deb http://repository.maemo.org/extras/ fremantle-1.3 free non-free
deb-src http://repository.maemo.org/extras-testing/ fremantle-1.3 free
deb http://repository.maemo.org/extras-testing/ fremantle-1.3 free non-free
deb-src http://repository.maemo.org/extras-devel/ fremantle-1.3 free
deb http://repository.maemo.org/extras-devel/ fremantle-1.3 free non-free
```
and following /etc/apt/preferences:
```
Package: *
Pin: release l=Extras-testing
Pin-Priority: 800

Package: *
Pin: release l=Extras-devel
Pin-Priority: 1000
```
After that, i had to run
```
fakeroot apt-get update
fakeroot apt-get install automake
fakeroot apt-get install libtool
```
I have manually installed libfreetype6-navit packages from bokomoko.
And build seems to run now (fingers crossed).

But I was also suggested at maemo irc to switch to ccsu-thumb instead of scratchbox, see http://mg.pov.lt/maemo-irclog/%23maemo.2016-01-10.log.html#t2016-01-10T00:51:26 and to "add navit it to extras" http://mg.pov.lt/maemo-irclog/%23maemo.2016-01-10.log.html#t2016-01-10T00:54:52

Maybe ccsu-thumb would be better integrable with circleci. And of course we'd be happy to be included in the official repo.

**Comment by ernesto75** [comment]
Cool! Thanks for the effort. So now you can build with autotools and also
cmake? After that is easy to add to maemo repos. :-)
Ps: i consider thumb version optional
Cssu-thumb is nice, but not everybody uses (maybe 20% of devices) 80% of
maemo users use just cssu. the problem is you have to install a fresh new
maemo version and not all the packages are built on thumb.
Il 10/gen/2016 00:15, "mdankov" <notifications@github.com> ha scritto:

**Comment by mdankov** [comment]
Up to now, I have managed to build R6024 with autotools. Did not test the built package though.
Then i have switched to cmake, at first it was crashing with sigsegv. I guess it's because i have installed cmake after i have added 'extra' repos to sources.list. SIGSEGV's are gone after i have switched to a fresh vm, taking care to install cmake before changing sources.list.

Build of current code with cmake has failed, because currently gtk_drawing_area works through cairo, and it was never tested if n900 version of cairo is supported. I guess, it at least has cairo. I'm now building 7410ba6, which i expect to be the last revision clean from that transition.

At navit irc channel, _rd shared following infos:
> If you just want to install a dpkg, I have
> deb http://bokomoko.de/~rd/maemo unstable/
> in my /etc/apt/sources.list.d/hildon-application-manager.list
> the release 0.5.0+dfsg.1-1maemo1~6012 is somewhat outdated, but it did not build for me  anymore (I had some local patches which caused conflicts during an update).
> Later something else broke in addition (which I do not remember anymore). With the transition to cmake the update path is entirely broken.
> I do not use my n900 anymore and unfortunately I have to much other stuff going on to care about the package myself.
> You are probably aware of this thread http://talk.maemo.org/showthread.php?t=38800&page=37 in the maemo forum.
> If you want to give your own build a chance, see http://talk.maemo.org/showpost.php?p=1448463&postcount=798
> It contains my build scripts and a very rudimentary description of the build process

**Comment by mdankov** [comment]
Another build stop while building gtk_drawing_area, probably it's dcc80ed3, require qt > 4.7

```
[  3%] Generating RenderArea.moc
Scanning dependencies of target graphics_qt_qpainter
[  3%] Building CXX object navit/graphics/qt_qpainter/CMakeFiles/graphics_qt_qpainter.dir/RenderArea.cpp.o
In file included from /home/maemo/navit/navit/graphics/qt_qpainter/RenderArea.cpp:19:
/home/maemo/navit/navit/graphics/qt_qpainter/graphics_qt_qpainter.h:66:24: error: QSvgRenderer: No such file or directory
make[2]: *** [navit/graphics/qt_qpainter/CMakeFiles/graphics_qt_qpainter.dir/RenderArea.cpp.o] Error 1
make[1]: *** [navit/graphics/qt_qpainter/CMakeFiles/graphics_qt_qpainter.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by mdankov** [comment]
Actually, here we are going to be sure if autotools removal doesn't break anything, so i'm now reverting to the head of ernesto75 branch (R6024), attempting to build it with cmake.

I do not think graphics problems are somehow in relation with makefile generator chosen (cmake/autotools). So we'll have to deal with graphics (and, probably, other) incompatibilities in separate branch(es).

**Comment by sleske** [comment]
> Build of current code with cmake has failed, because currently gtk_drawing_area works through cairo, and it was never tested if n900 version of cairo is supported. I guess, it at least has cairo.

Yes, that was me :-/. However, as far as I can see, the transition to Cairo should not be a problem for N900. GTK+ has used Cairo internally for a long time (at least since V2.8, from 2005), so if gtk_drawing_area worked on N900 before, it should work with Cairo, too.

At any rate, if the autotools build works, the use of Cairo cannot be the problem. If you can share the exact build error, maybe we can solve this together.

**Comment by mdankov** [comment]
sleske, i guess, Cairo problem is most probably just my fault to install appropriate development library in the build environment. I do not have a single successful cmake build yet, and concentrating on achieve it.

I had also to disable qt_qpainter graphics for now. Looks like cmake detects QSvgRenderer presence, but does  not properly configure its paths. At least, i have manually located that file in /usr/include/QtSvg, but during build i get:
```
[  3%] Building CXX object navit/graphics/qt_qpainter/CMakeFiles/graphics_qt_qpa
inter.dir/RenderArea.cpp.o
In file included from /home/maemo/navit/navit/graphics/qt_qpainter/RenderArea.cp
p:19:QSvgRenderer
/home/maemo/navit/navit/graphics/qt_qpainter/graphics_qt_qpainter.h:66:24: error
: QSvgRenderer: No such file or directory
make[2]: *** [navit/graphics/qt_qpainter/CMakeFiles/graphics_qt_qpainter.dir/Ren
derArea.cpp.o] Error 1
make[1]: *** [navit/graphics/qt_qpainter/CMakeFiles/graphics_qt_qpainter.dir/all
] Error 2
make: *** [all] Error 2
```
I'll also have to verify what autotools build thinks about QSvgRenderer presence on this platform.
Scratchbox has cmake 2.6.3 installed.

**Comment by mdankov** [comment]
I currently have successfully built navit-armel with plain cmake, and navit-i386 deb packages.

Though for now, I have qt_qpainter and gui/qt switched off, and using an older version of code from ernesto75 branch to keep away from gui_gtk switch to cairo.

Now building deb packages for armel with cmake. Armel builds are very slow.

@sleske, i think cairo in general is not of a big concern. Build fails on macro CAIRO_ANTIALIAS_GOOD, which is defined since 1.12, but maemo has cairo 1.8.

We can check cairo version at build time or just switch to  CAIRO_ANTIALIAS_DEFAULT, which is said to be typicaly equivalent to the former, see http://www.cairographics.org/manual/cairo-cairo-t.html#cairo-antialias-t.

**Comment by ernesto75** [comment]
Amazing results!

I am glad for maemo community to still have the possibility to install a 
fresh Navit deb, even from the repos (hopefully with cairo)!

Thank you again for your work.



Il 16/01/2016 08:33, mdankov ha scritto:

**Comment by mdankov** [comment]
Ok, i now have some deb files for testing: http://www.navit-project.org/~tryagain/maemo/

There's also the source tarball with cmake-aware debian folder.

I have changed option to build only two size versions of images to make the build run faster, so don't be surprised by blurred imagery. Though, one maybe can use an old data package or put png images directly to /opt/navit/share/navit/xpm. Uhhh, i'll have to deal with that path.

Now will attempt to switch to a more current code version.

**Comment by ernesto75** [comment]
Installed the armel debs (except the data one, which i kept from other
build)  It works. Ready to test newest one
Il 16/gen/2016 18:26, "mdankov" <notifications@github.com> ha scritto:

**Comment by mdankov** [comment]
@ernesto75 , now i have success pushing our git master head source to the maemo official autobuilder, and it even has built with cmake and propagated to extras-devel repo.
So please check if it works for you. There should be a full set of images available in navit-data.

I also see there's a patch for navit_shipped.xml laying in debian/patches.orig. I did not test it yet, but have a few questions regarding it. 

1. There's an osd layout defined. I think we should include some usable and n900-tested osd layout before attempting to move to extras-testing. Should we start with that layout, or maybe you have your own which would fit better?
2. There's an attempt to use espeak speech module. I don't think it would work at all, as it's windows-only plugin. I expect <speech type="cmdline" data="espeak '%s'" cps="15"/> to have more chances to work on n900.
3. The patch enables two mapsets at the same time. That's not the way to go.

I still have graphics/qt_qpainter and gui/qml disabled for maemo builds. Do you think they are indeed useful on n900?

**Comment by ernesto75** [comment]
Great! Is the latest one with cairo? Im going to test it asap!
I can attach the config files i use. I have it in /home/user/.navit  
The OSD.xml is ok for the N900, little mods and personalizations are still possible like odometer etc. 
Espeak works also on maemo, we have espeak package in repos
my speech.xml now is also using mbrola voices to improve voice quality (less robotic) but i put an arm bin from mbrola manually on my N900 (i wrote an howto about it)

Don't know about patch enabling two mapsets at the same
time, in my xml i just point at one bin map


graphics/qt_qpainter i tried once from bokomoko repo to see if improve performance but with internal gui didn't appreciate improvements, maybe with other guis? qml gui also i tried from bokomoko it seems buggy and unusable (discontinued developing?) So i can wait for that.


> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/navit-gps/navit/pull/62#issuecomment-172343429

odometer persistent_odometer_1 0.000000 0.000000 0 0.000000

navit.layout=navit.layout[@name=="Car"];

**Comment by ernesto75** [comment]
The version in maemo repos working good! I just noticed a wrong icon for
car parking, its a blu square but the P is missing
Il 17/gen/2016 21:35, "Fabri" <erfabbri@gmail.com> ha scritto:

**Comment by mdankov** [comment]
@ernesto75, cool.
I think we should fix the parking icon because it currently depends on specific font being installed on the device which interprets the svg file (build server in this case).
Please share your current navit configuration so we can include it in maemo builds as a default one.

**Comment by ernesto75** [comment]
I put my config files, with some screenshots about the wrong car parking 
icon, here in Dropbox 
https://www.dropbox.com/sh/jp6mzwstroran5o/AADEHGk2Ya69MmpV7wx8n_08a?dl=0

**Comment by sleske** [comment]
@mdankov:
>  I think we should fix the parking icon because it currently depends on specific font being installed on the device which interprets the svg file (build server in this case).

Yes, parking.svg currently contains a "<text>" element to render the "P", with font Bitstream Vera Sans Bold. It should be simple to convert this to a vector path  (in Inkscape, "Path / Object to path"). I'll see if I can fix this.

**Comment by mvglasow** [comment]
@mdankov @ernesto75 As for the OSD configuration – this is definitely something that needs to be worked on, but I think this is a separate discussion and it concerns a few more platforms. (For example, the default Android OSD layout could also use an overhaul – I already have some ideas on that.) I'd suggest opening a ticket for the OSD – the purpose of this merge request is to ensure we can build all ports with the cmake toolchain.

**Comment by sleske** [comment]
What is the current state of this issue? It would be great if we could finally drop autotools.
As far as I can see, this PR is ready to be merged. Or are there any major problems remaining?

**Comment by ernesto75** [comment]
Maemo version now can compile with cmake. Just a secondary issue to fix is
the push to maemo repos. Has been reported to be slow on rendering. I don't
no if this is due to the hardware or to the cairo version in maemo1.8 or an
old xml

What is the current state of this issue? It would be great if we could
finally drop autotools.
As far as I can see, this PR is ready to be merged. Or are there any major
problems remaining?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/navit-gps/navit/pull/62#issuecomment-218410598>

**Comment by sleske** [comment]
@ernesto75 
> Maemo version now can compile with cmake. Just a secondary issue to fix is the push to maemo repos. 

I'm afraid I don't understand - could you explain what you mean by "fix the push to maemo repos"? Does Maemo not just pull the source code via git or similar?

>Has been reported to be slow on rendering.

Could you explain what "slow rendering" has to do with this ticket? This is about changing the build system. Changing the build system should not change the compiled code - the compiler invocations should remain the same, they are just generated differently. If the switch automake -> cmake produces different code, we should investigate that.

**Comment by jandegr** [comment]
Is there something else to do for the original topic, now tomtom is converted to cmake ?

**Comment by pgrandin** [comment]
Updating the branch to match the current trunk

**Comment by george-hopkins** [comment]
As all conflicts have been resolved, are there any issues that need to be resolved?

**Comment by george-hopkins** [comment]
@jandegr Thanks for merging!

**Pull request merged**
