### PR TITLE
Fix latlon2bookmark

### PR DESCRIPTION
**Pull request by jkoan**
This PR Fixes two minor Bugs wit latlon2bookmark. Now its possible to compile it again

### CODE REVIEW

**Comment by pgrandin** [comment]
Thanks @jkoan !
Maybe we should add a step in the CI to test the different scripts / extra tools that we have?

**Comment by jkoan** [comment]
Or add it to cmake build?

**Comment by pgrandin** [comment]
Yeah we could have an "extra" or "tools" section there.

**Comment by jkoan** [comment]
I will merge this now and add other things like the cmake integration later

**Pull request merged**
