### PR TITLE
fix:maptool: Don't drop unrecognized relations to borders temp file

### PR DESCRIPTION
**Pull request by metalstrolch**
Cleans up place to area processing

### CODE REVIEW

**Comment by jkoan** [comment]
Can you explain whats the current problem is about filtering out type_none?

**Comment by metalstrolch** [comment]
We're currently not filtering out type_none. Instead, we drop everything NOT type_none into the boundaries file. Regardless if it is actually a boundary according to our needs. This has the effect that boundary processing takes far longer than required.

**Comment by jkoan** [comment]
> We're currently not filtering out type_none. Instead, we drop everything NOT type_none into the boundaries file. Regardless if it is actually a boundary according to our needs. This has the effect that boundary processing takes far longer than required.

Got it! Now i also see the logic error.

**Comment by jkoan** [comment]
> @jkoan , do you know why ci fails on "trunk" for linux_build during updating of the translation files to/from launchpad? Or do you think I should open a ticket about this?

i know more or less what its about. You don't need to open up a ticket, i will take care of it

**Comment by metalstrolch** [comment]
Thanks.

**Pull request merged**
