### PR TITLE
enhancement:layout_car:use transparency to draw some map features

### PR DESCRIPTION
**Pull request by metalstrolch**
With the introduction of the multipolygon code we now have all the nice landuses in the map. However, in OSM there are some map features that are not mapped as multipolygon but just "above" the other landuses. Like poly_zoo, poly_theme_park or poly_airfield.
Current configuration causes them to be hidden by the landuses, as these are drawn after the above mentioned. OSM's Mapnik style solves the problem by drawing those feature transparent above the landuses.
This pull request does so for some map features as well causing the map to look way better.

If transparent drawing is not supported by the platform, this causes the mentioned polys to be drawn above the landuses, showing them, eventually hiding some landuse details underneath. But this looks even better than before too.

NOTE: Transparent drawing is known to work on: Qt5 (sailfish) and gtk.
NOTE: Transparent drawing is known NOT to work on SDL
Dont't know for all the others. Sombody might want to check Android? Remember #852 on comparing screenshots though.

### CODE REVIEW

**Comment by metalstrolch** [comment]
See the difference on the small snippet near Ammersee, Munich:
zoo_solid
zoo_transparent
Note the airport on the upper left corner, and the "zoo" in the center. The zoo is drawn as a transparent outline only, the Airport is tinted by overlaying the shape transparent.

**Comment by jkoan** [comment]
I did realignment and diffed the images. The Purple paths are where the PR makes changes:
diff

**Comment by metalstrolch** [comment]
Wow thats cool. I was too lazy to do show it like that.
Most changes are due to giving meadows a lighter color. Nothing unexpected.

Android anyone?

Do we like that?

**Comment by metalstrolch** [comment]
If no objections going to merge this at Fr, 27th of September.
I like it.

**Comment by metalstrolch** [comment]
OK, merging this even if it's not friday yet

**Pull request merged**
