### PR TITLE
Curley distance poi

### PR DESCRIPTION
**Pull request by charlescurley**
fix:gtk:poi Distances to POIs can now be shown in feet.

### CODE REVIEW

**Comment by jkoan** [comment]
If you are working on Commandline, a simple `git rebase trunk` should be enought ;) if this is not working probably origin/trunk or something like this

**Comment by charlescurley** [comment]
On Wed, 22 Aug 2018 08:31:55 -0700
jkoan <notifications@github.com> wrote:

> If you are working on Commandline, a simple `git rebase trunk` should
> be enought ;) if this is not working probably origin/trunk or
> something like this

OK, I've gone as far as I can.

One lesson: do NOT edit the .po files (e.g. po/en_GB.po.in)! Something
that runs during build time (I think) updates them for you. Editing
them for yourself results in conflicts that git doesn't like and you
have to resolve by hand.

Would someone kindly add that to the docs. Thank you.

I did a git clone to get the latest & greatest onto my computer. That
didn't have the branch in question. So I did "git clone -b
curleyDistancePoi...", and that got the latest with the branch I
wanted. I then started the rebase, which was a mess.

charles@hawk:~/versioned/navit$ git rebase --skip
charles@hawk:~/versioned/navit$ git st
On branch curleyDistancePoi
Your branch and 'origin/curleyDistancePoi' have diverged,
and have 7 and 6 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
nothing to commit, working tree clean
charles@hawk:~/versioned/navit$ git commit -a
On branch curleyDistancePoi
Your branch and 'origin/curleyDistancePoi' have diverged,
and have 7 and 6 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
nothing to commit, working tree clean
charles@hawk:~/versioned/navit$ 


Now what?

-- 
"When we talk of civilization, we are too apt to limit the meaning of
the word to its mere embellishments, such as arts and sciences; but
the true distinction between it and barbarism is, that the one
presents a state of society under the protection of just and
well-administered law, and the other is left to the chance government
of brute force."
- The Rev. James White, Eighteen Christian Centuries, 1889
Key fingerprint = CE5C 6645 A45A 64E4 94C0  809C FFF6 4C48 4ECD DFDB
https://charlescurley.com

**Comment by jkoan** [comment]
I have done the rebase and pushed it on the repo, could you please verify that this exacly what you want to get merged?

**Comment by charlescurley** [comment]
On Mon, 27 Aug 2018 15:50:30 +0000 (UTC)
jkoan <notifications@github.com> wrote:

> I have done the rebase and pushed it on the repo, could you please
> verify that this exacly what you want to get merged? 

Yes. The code looks right. It builds and runs, and the UI looks right.

Thank you.

Obviously I have some things to learn about rebasing.

-- 
"When we talk of civilization, we are too apt to limit the meaning of
the word to its mere embellishments, such as arts and sciences; but
the true distinction between it and barbarism is, that the one
presents a state of society under the protection of just and
well-administered law, and the other is left to the chance government
of brute force."
- The Rev. James White, Eighteen Christian Centuries, 1889
Key fingerprint = CE5C 6645 A45A 64E4 94C0  809C FFF6 4C48 4ECD DFDB
https://charlescurley.com

**Comment by charlescurley** [comment]
On Mon, 27 Aug 2018 15:50:30 +0000 (UTC)
jkoan <notifications@github.com> wrote:

> I have done the rebase and pushed it on the repo, could you please
> verify that this exacly what you want to get merged? 

I assumed that what you wanted me to check was in the branch
curleyDistancePoi. Is that correct?

-- 
"When we talk of civilization, we are too apt to limit the meaning of
the word to its mere embellishments, such as arts and sciences; but
the true distinction between it and barbarism is, that the one
presents a state of society under the protection of just and
well-administered law, and the other is left to the chance government
of brute force."
- The Rev. James White, Eighteen Christian Centuries, 1889
Key fingerprint = CE5C 6645 A45A 64E4 94C0  809C FFF6 4C48 4ECD DFDB
https://charlescurley.com

**Comment by jkoan** [comment]
Yes, i also need to improve my merge and rebase workflow, i made a mistake in this progress :/ but if its okay now i would like that @pgrandin also looks on the code and merges when approved ;)

**Comment by pgrandin** [comment]
The changes to the .po.in files will need to be backported to launchpad.
The translation template is generated via the CI and pushed to launchpad, then we import the .po.in files from launchpad into the VCS. ( https://wiki.navit-project.org/index.php/Translations )

In the future we should refrain from pushing changes to .po.in files directly as they will be lost anyway.

Otherwise the change looks good, thanks @charlescurley !

**Comment by charlescurley** [comment]
On Wed, 29 Aug 2018 23:08:12 -0700
Pierre GRANDIN <notifications@github.com> wrote:

> The changes to the .po.in files will need to be backported to
> launchpad. The translation template is generated via the CI and
> pushed to launchpad, then we import the .po.in files from launchpad
> into the VCS. ( https://wiki.navit-project.org/index.php/Translations
> )

All good stuff to know.

> 
> In the future we should refrain from pushing changes to .po.in files
> directly as they will be lost anyway.

I quite agree. I did not read any of the stuff for translators because
I wasn't translating. So I wasn't aware of this process. Please
document this for developers so that others don't make the same mistake.

Thanks


> 
> Otherwise the change looks good, thanks @charlescurley !
> 

You are welcome.

-- 
"When we talk of civilization, we are too apt to limit the meaning of
the word to its mere embellishments, such as arts and sciences; but
the true distinction between it and barbarism is, that the one
presents a state of society under the protection of just and
well-administered law, and the other is left to the chance government
of brute force."
- The Rev. James White, Eighteen Christian Centuries, 1889
Key fingerprint = CE5C 6645 A45A 64E4 94C0  809C FFF6 4C48 4ECD DFDB
https://charlescurley.com

**Pull request merged**
