### PR TITLE
Fix:CI:Make sure the wince build fails when make or cmake fail

### PR DESCRIPTION
**Pull request by aerostitch**
Closes: #455
1st run should fail on wince, then I'll work on the underlying issue.

### CODE REVIEW

**Comment by aerostitch** [comment]
Ok, so the 1st commit works as expected. :)

**Comment by aerostitch** [comment]
The wince issue has been introduced by https://github.com/navit-gps/navit/commit/54dac2a0f22efbe15d4b081d69881a344bdc0419 in #441
@jandegr FYI

**Comment by aerostitch** [comment]
So I fixed the inner issue (the absence of `fmin`/`fmax` on wince) by using the `MIN`/`MAX` macros we defined in gmacros.
Now it works and I don't think that will be a problem because we are comparing int.
@jandegr can you confirm that this change is ok for you please?

Thanks
Joseph

**Comment by pgrandin** [comment]
Nice, thanks @aerostitch for taking care of that!

**Comment by aerostitch** [comment]
`set -e` works too.
I updated the PR to use `set -e`, it works as expected.

**Pull request merged**
