### PR TITLE
Update:i18n:Updated Swedish translation from launchpad

### PR DESCRIPTION
**Pull request by hoehnp**
Thanks for contributing to Navit!
Before opening a pull request on navit, make sure your commit message follows our guidelines:
https://navit.readthedocs.io/en/trunk/development/commit_guidelines.html

and that your code is compliant with out coding style guidelines:
https://navit.readthedocs.io/en/trunk/development/programming_guidelines.html

### CODE REVIEW

**Comment by jkoan** [comment]
Still WIP?

**Comment by hoehnp** [comment]
possibly next week on the weekend I can revisit this issue. @jkoan: if you want you can merge the intermediate version and I open a new PR later on.

**Comment by hoehnp** [comment]
@pgrandin: any clue why despite using pull --rebase the branch is still out of date?

**Comment by pgrandin** [comment]
@hoehnp looks like @jkoan fixed it for you :)

**Pull request merged**
