### PR TITLE
Add:gui/internal: Greek keyboard

### PR DESCRIPTION
**Pull request by OLFDB**
Add:gui/internal: Greek keyboard

### CODE REVIEW

**Comment by mvglasow** [comment]
Can I ask you to rework your code?

You are reformatting the code in a number of places, making it very hard to see what has changed. If you feel sections of the code need to be reformatted, please do so in a separate commit and make it clear in the commit message that this is a mere refactoring, with no functionality changed.

Also, I see you have changed some Doxygen comments (starting with `/**` or `/**<`) into regular ones, meaning that the respective declarations will no longer appear in the documentation. Please refrain from doing that—we are working hard on documenting our code. (While I am aware of the argument that the source code should be self-explanatory, there are limits to that. Even well-written code can only explain *what* you are doing, but not *why* you are doing it.)

**Comment by OLFDB** [comment]
I cant't get the checks passed. What is wrong here?

#!/bin/bash -eo pipefail
bash scripts/ci_sanity_checks.sh

[INFO] Checking for trailing spaces on navit/gui/internal/gui_internal_keyboard.c...
[INFO] Checking for indentation and style compliance on navit/gui/internal/gui_internal_keyboard.c...
Formatted  navit/gui/internal/gui_internal_keyboard.c
diff --git a/navit/gui/internal/gui_internal_keyboard.c b/navit/gui/internal/gui_internal_keyboard.c
index 90cbc85df..5ef20af39 100644
--- a/navit/gui/internal/gui_internal_keyboard.c
+++ b/navit/gui/internal/gui_internal_keyboard.c
@@ -283,7 +283,7 @@ gui_internal_keyboard_do(struct gui_priv *this, struct widget *wkbdb, int mode)
         } else {
             if (mode==VKBD_GREEK_UPPER)
                 MODE(VKBD_GREEK_LOWER);
-			else
+            else
                 MODE(VKBD_GREEK_UPPER);
             MODE(VKBD_CYRILLIC_UPPER);
             MODE(VKBD_CYRILLIC_LOWER);
[ERROR] You may need to do some cleanup in the files you commited, see the git diff output above.
[INFO] Checking for trailing spaces on navit/gui/internal/gui_internal_keyboard.h...
Exited with code 1

**Comment by OLFDB** [comment]
Found it: mode==VKBD_GREEK_UPPER -> mode == VKBD_GREEK_UPPER

**Comment by mvglasow** [comment]
Looks better now. Thanks!

**Comment by lains** [comment]
Hello @OLFDB, thanks for your nice work.
Please do not hesitate to help us improve also the doxygen comments by submitting a separate PR as @mvglasow mentionned.
There are many functions, enums, structs etc. that are not yet documented.
The result of doxygen generation of the code is available [here](http://doxygen.navit-project.org/index.html).

**Pull request merged**
