### PR TITLE
Add poly_basin

### PR DESCRIPTION
**Pull request by jfitie**
https://github.com/navit-gps/navit/pull/240#issuecomment-299689298

### CODE REVIEW

**Comment by jandegr** [comment]
Hi,
If you can confirm it displays properly I will merge it, can't run QA on an external fork as is.

**Comment by jfitie** [comment]
Before and after:

screenshot_2017-05-08-21-26-56

screenshot_2017-05-08-21-27-54

**Comment by jandegr** [comment]
nice, thx, but branch has merge conflicts .......
@kazer ?

**Comment by jfitie** [comment]
Hope this solved the conflict ...

**Comment by sleske** [comment]
Could you simply rebase your commit? Would make for a nicer commit history :-).

**Pull request merged**
