### PR TITLE
Fix:POI/poly/labels:Small visual improvements to POI order, poly colors, and labels

### PR DESCRIPTION
**Pull request by jfitie**
Small visual improvements to POI order.
Also fixed POI order in `navit_layout_car_dark_shipped.xml`, which is now the same as in `navit_layout_car_shipped.xml`.

### CODE REVIEW

**Comment by jfitie** [comment]
Why does this PR fail?

**Comment by metalstrolch** [comment]
OK, then this isn't only with my setup. It seems that currently android build fails on branchs that are not on navit-gps but on users fork. Here on jfiftie. Noticed that on builds for my branches as well. But I don't have a clue why.

**Comment by metalstrolch** [comment]
Pushed the same branch to navit-gps repository. Let's see if this builds.

**Comment by metalstrolch** [comment]
Funny. Now the branch on navit-gps finished CI, this PR is green as well.

**Comment by jfitie** [comment]
@metalstrolch Is this good enough to merge? If so, please go ahead.
Hope this brings a bit more consistency to the default map layout

**Comment by jfitie** [comment]
Removed the `navit-gps:smallvisimprov` branch

**Comment by jfitie** [comment]
@metalstrolch Is this good enough to merge? If so, please go ahead.
Hope this brings a bit more consistency to the default map layout

**Comment by jfitie** [comment]
@metalstrolch Is this good enough to merge? If so, please go ahead.
Hope this brings a bit more consistency to the default map layout

**Pull request merged**
