### PR TITLE
Cleanup:global:Use astyle to reformat everything

### PR DESCRIPTION
**Pull request by aerostitch**
This PR uses the config file in #568 to reindent everything.
Commands used:
```
find . -iname '*.c' -o -iname '*.cpp' -o -iname '*.h' -exec indent -gnu -l200 {} \;
# indent generates backup files that you need to delete
find . -iname '*~' -delete
```

I put that in a separate PR to allow more clarity.
As we update the other PR I'll update this one too.
1st iteration is using `-gnu --line-length=200`

Note that when I can that I got:
```
indent: ./navit/data.h:38: Warning:old style assignment ambiguity in "=*".  Assuming "= *"
                                                                                
indent: ./navit/data.h:50: Warning:old style assignment ambiguity in "=*".  Assuming "= *"
                                                                               
indent: ./navit/data.h:77: Warning:old style assignment ambiguity in "=*".  Assuming "= *"
                                        
indent: ./navit/data.h:89: Warning:old style assignment ambiguity in "=*".  Assuming "= *"
                                         
indent: ./navit/gui/qml/searchProxy.h:30: Warning:old style assignment ambiguity in "=&".  Assuming "= &"
                                                      
indent: ./navit/gui/qml/ngqpoint.h:268: Warning:old style assignment ambiguity in "=-".  Assuming "= -"
                                          
indent: ./navit/gui/qml/ngqpoint.h:272: Warning:old style assignment ambiguity in "=-".  Assuming "= -"
                                                         
indent: ./navit/gui/qml/ngqpoint.h:319: Warning:old style assignment ambiguity in "=*".  Assuming "= *"
                                                         
indent: ./navit/gui/qml/ngqpoint.h:341: Warning:old style assignment ambiguity in "=*".  Assuming "= *"
                                                     
indent: ./navit/gui/qml/routeProxy.h:18: Warning:old style assignment ambiguity in "=*".  Assuming "= *"
                                                       
indent: ./navit/gui/qml/routeProxy.h:23: Warning:old style assignment ambiguity in "=*".  Assuming "= *"
                                                  
indent: ./navit/support/glib/galias.h:0: Error:Zero-length file ./navit/support/glib/galias.h
indent: ./navit/support/espeak/speak_lib.h:145: Warning:old style assignment ambiguity in "=-".  Assuming "= -"
                                                    
indent: ./navit/debug.h:44: Warning:old style assignment ambiguity in "=-".  Assuming "= -"
                                                    
indent: ./navit/map.h:113: Warning:old style assignment ambiguity in "=&".  Assuming "= &"
                                                               
indent: ./navit/map.h:155: Warning:old style assignment ambiguity in "=&".  Assuming "= &"
                                                                           
indent: ./navit/map.h:186: Warning:old style assignment ambiguity in "=&".  Assuming "= &"
```

### CODE REVIEW

**Comment by aerostitch** [comment]
There's definitely something wrong with the way indent sees `ATTR*`. I'll have to look into that

**Comment by pgrandin** [comment]
Actually `astyle` seems to do a better job at handling `attr_def.h` and our various `#ifdef __cplusplus`

`astyle --indent=tab=8 --style=kr ...`

**Comment by aerostitch** [comment]
Updated the PR.
The command to reformat I used is:
```
find . -type f  \( -not -path './navit/support/*' \) -a \( -iname '*.c' -o -iname '*.cpp' -o -iname '*.h' -o -iname '*.java' \) -exec astyle --indent=tab=8 --style=kr -n {} \;
```

**Comment by metalstrolch** [comment]
While I really like having automatic coding style, there are two major problems with introducing it this hard way:
1. It will render most of the open branches useless, as none would merge any more probably.
2. It may break compilation because things like headers requiring a defined include order. This could be avoided by not having a style sorting the includes. For example the qt5 graphics will break if you change the order of the include files. I learned that from using clang-format on those files...

**Comment by pgrandin** [comment]
Thanks @metalstrolch ! My 2 cents:

>    It will render most of the open branches useless, as none would merge any more probably.

True. We do not need to merge the PR right now as @aerostitch is generating the change with a script.
We have 2 possibilities : merge all possible PRs before applying this change (and fix whatever will need to be fixed on the remaining ones) or start a branch like 0.6.0 with this refactoring, that we'll merge later. What are your thoughts?

>    It may break compilation because things like headers requiring a defined include order. This could be avoided by not having a style sorting the includes. For example the qt5 graphics will break if you change the order of the include files. I learned that from using clang-format on those files...

Yeah, also applying the K&R style on the headers make them look ugly. I agree that we should skip them.

**Comment by aerostitch** [comment]
Hi @metalstrolch,

To answer your points (which are totally valid):
1. I can rebase the branches if they are up-to-date in the repo and am able to identify who's working on it (to ping him/her, making sure he/she will pull the branch before pushing any more changes.
2. for the headers we can either exclude them entirely or have different style options, safer ones. which one do you prefer.

We're currently experimenting with `astyle` and we'll try to enforce that later on so if you have suggestions, we're totally open to it! :)

**Comment by metalstrolch** [comment]
No you cannot notify people working on it. I for example had  the qt5 branches locally for almost two years. Nobody knew that. Changing the whole codebase at once will render such works unusable. This may disappoint a lot of people. Of course here we may never be presented the results then.

But maybe the experiments lead to finally fixing our headers so the order shouldn't matter. But that's a different story.

**Comment by aerostitch** [comment]
My bad I thought you were talking about branches that are currently in the repo.
What are your suggestions then?
The problem with this is that if I touch any file in the repo I might end up annoying someone because he/she would have to rebase/merge their local changes. Would you prefer that we don't do any cleanup? :(

**Comment by metalstrolch** [comment]
It's all about timing then. And it's about giving hints on how to rescue your work.
This should be waged against the benefits from using a tool to "clean" the code.

Think of all the snippets floating around like the proposal for multipolygon support posted as a patch to trac long ago.

I still really like the idea (and used clang-format for my work as well).
But all of us should know and think of all the consequences.

**Comment by aerostitch** [comment]
I can surely wait a week or so and ping @jandegr, @sleske, @mdankov, @jfitie, @jkoan, @pohlinkzei, @hoehnp, @charlescurley, @mvglasow, @xenos1984 and maybe the rest of the @navit-gps/navit team in this issue, so that everybody has time to voice their potential issues there.

Rebasing this PR is really easy for me, it's just a matter of `git reset --hard HEAD^ && git pull --all && git merge upstream/trunk` before regenerating the cleanup commit with the following (I just updated it to not include the headers file in the reformatting), then I push and it's done, so really no biggy :smiley: :
```
find . -type f  \
 \( -not -path './navit/support/*' -a -not -path './navit/fib-1.1/*' \) \
 -a \( -iname '*.c' -o -iname '*.cpp' -o -iname '*.java' \) \
-exec \
 astyle --indent=tab=8 --style=kr -n  --break-return-type-decl --max-code-length=120 {} \;
```

Note that after this patch is merged, I'm also totally open to:
* get the branches up-to-date with latest version as long as people let me know which ones they need (and that they push their branches to the repo so that I can access them). After I'm done they'd just need to pull and it would be all good
* integrate the patches in up-to-date branches if people let me know which ones. I can look around in trac and make branches for trac tickets that have a patch if you want. If that can help I'll do it gladly

Note that if pushing directly in branches of the navit-gps/navit repo (and not in a fork), we might want to start to put the name of the person working on it in front of it so that it's easier to ping the right person when doing cleanup or helping on getting them up-to-date. What do you think?

**Comment by pgrandin** [comment]
Kudos for the help you're offering here, @aerostitch 
:+1: :rocket:

**Comment by aerostitch** [comment]
Let's target a merge on the May the 9th then.

**Comment by aerostitch** [comment]
So I'd like to add something to remove trailing spaces too but for all the files this time like:
```
find . -type f -exec sed 's/\s*$//' -i {} \;
```
And maybe also to find an easy way to have consistency between tabs and spaces in `CMakelist.txt` (by mimicking a vim retab function).
What do you think?

**Comment by pgrandin** [comment]
@metalstrolch any concerns with @aerostitch 's plan to merge soon?
Our fear of breaking things is what prevented us from doing it in the past, but we need to improve our codebase.

**Comment by mvglasow** [comment]
Sounds good to me, I have just one question: Since I have a branch in the pipeline (forked before the Great Cleanup, to be merged after), how do I prevent tons of merge conflicts?

My first approach would be:

* Run the same cleanup against my branch
* Merge master into it (which should not cause any conflicts due to formatting changes, because both branches have changed in identical ways)
* Continue developing
* Finally run cleanup once more before I file a merge request

Is that the recommended way to go? Or is there another?

Are the steps to execute documented in a foolproof way (i.e. command lines in the exact order)? Since I understand all new code will be expected to comply with these formatting guidelines, maybe it would make sense to include a shell script for the cleanup, which I just need to run before merging.

**Comment by aerostitch** [comment]
It depends how many commits you have.
The cleanest approach I would take would be:
```shell
# Make sure everything is commited:
git commit -am 'backup before cleanup'
# export your changes as patches. If you have 10 commits that have not been merged for example:
git format-patch HEAD~10
# This will generate 1 file per commit in the current directory, so move them into a safe place, for example your home directory/backup_navit
mkdir ${HOME}/backup_navit
mv *.patch ${HOME}/backup_navit
# then update trunk (I'm assuming you're not working on a fork here)
git checkout trunk
git pull --all
# go back in your branch, remove all your commits (we're still assuming 10 here)
git checkout your_branch
git reset --hard HEAD~10
# merge with trunk making sure you fast-forward only
git merge trunk --ff-only
#finally reapply your patches 1 by 1 (you will have to recreate a commit for each patch
patch -p1 < ${HOME}/backup_navit/0001-my_patch_name.patch
git commit -am 'Your commit message for that patch'
# do those last 2 lines for each patch and you will have fully rebased your branch
# then you push using --force on your branch
```
Note that you might have to deal with rejected patches at some points but the patch files are just git diffs so you can edit them easily.
How far behind is your branch? If not too far it'll be easy (generally the patch command is pretty good at dealing with that).

The cleanup shell script will require you to have the `astyle` command install and it would be (assuming you're running linux):
```shell
find . -type f  \
 \( -not -path './navit/support/*' -a -not -path './navit/fib-1.1/*' \) \
 -a \( -iname '*.c' -o -iname '*.cpp' -o -iname '*.java' \) \
-exec \
 astyle --indent=tab=8 --style=kr -n  --break-return-type-decl --max-code-length=120 {} \;

git commit -am 'cleanup:global:Use astyle to reformat everything'

find . -type f \( -not -path './navit/support/*' -a -not -path './navit/fib-1.1/*' -a -not -path './.git/*' \) \
  -a \( -not -iname '*.bat' \) | while read f; do \
   [[ "$(file -bi $f)" =~ ^text ]] && sed 's/\s*$//' -i $f; done

git commit -am 'cleanup:cmake:remove trailing spaces'

find . -iname 'CMakeLists.txt' -exec ex +"set syn=cmake" +"set noexpandtab" +"norm gg=G" -cwq {} \;

git commit -am 'cleanup:cmake:retab all CMakeLists.txt files'
```

**Comment by aerostitch** [comment]
Holly molly, 236 commits, that indeed changes a lot of things! :smiley: 
It is pretty stable. If you see stuffs that you don't like in the current commits, then we can change the command but as long as everybody's happy with it it won't change.
Note that the last find command will require you to have `vim` installed.

**Comment by mvglasow** [comment]
Yep, adding live traffic is no small thing :-) I’ll merge `trunk` once more, then QA it as described and report back.

There are only a few things I would change in the script (no impact on the code itself):

* If all code changes are automated, we don’t really need three separate commits—that can be committed all at once.
* I’d advise against `git commit -a`, as it makes it all too easy to commit things you didn’t mean to—or miss new files which are not yet being tracked. (In one of my other projects I use submodules, and if one of those isn’t up to date, running `git commit -a` is a recipe for disaster.) My general recommendation is to use a GUI tool or review the changes on the command line before committing. Here, we could simply not bother with it and at the end tell the user to commit the changes made by the script.
* If this is to become a script, then I would add an initial check if the repo has uncommitted changes and, if that is the case, let the user choose what to do (abort, proceed, stash and proceed, …)

**Comment by aerostitch** [comment]
> If all code changes are automated, we don’t really need three separate commits—that can be committed all at once.

Yes, I separated them just to make it clearer for the code review.

> I’d advise against git commit -a, as it makes it all too easy to commit things you didn’t mean to—or miss new files which are not yet being tracked.

Yes, I know, it was just there for easier use but in general I specify the files of at least use `git status` and `git diff` before committing anything (if several files, git diff of each file and fit add when I'm done with the review).

> If this is to become a script, then I would add an initial check if the repo has uncommitted changes and, if that is the case, let the user choose what to do (abort, proceed, stash and proceed, …)

Yes that's the idea behind using a pre-commit hook.

**Comment by jandegr** [comment]
pls consider using it with  style=java and 4 spaces for java files
thx

**Comment by mvglasow** [comment]
I’ve created a shell script for the cleanup, which you can find at https://github.com/mvglasow/navit-goodies/blob/master/scripts/cleanup/cleanup.

About `style=java`, is there any good reason not to use that for all files, Java and C alike? In fact I prefer

    sometype someFunc() {
        // code here
    }

over

    sometype
    someFunc()
    {
        // code here
    }

—the first example is much more compact, allowing me to view more information in the same amount of screen real estate. It’s also how Eclipse formats code by default (the only IDE for which we have documented support). Also, having a consistent style guide across C and Java is easier for devs to deal with and less coding work to automate.

I realize the programming guidelines on our wiki mention K&R style, but that isn’t set in stone, and if we are to change it, it is easiest to do that now.

**Comment by mvglasow** [comment]
Something isn’t working as expected. When I apply the cleanup script to two branches and merge them, I get a couple of these in `CMakeLists.txt` and `navit/CMakeLists.txt`:

```
@@@ -161,12 -161,12 +166,17 @@@ endif ()add_executable (navit 
  
  )if (DEFINED NAVIT_BINARY)
    set_target_properties (navit PROPERTIES OUTPUT_NAME $
  			 {
  			 NAVIT_BINARY}
  <<<<<<< HEAD
 +)endif (DEFINED NAVIT_BINARY) ifindent: Standard input:100: Error:Unmatched 'else'
 + (BUILD_BUNDLE)
  =======
+ )endif (DEFINED NAVIT_BINARY) if (BUILD_BUindent: Standard input:100: Error:Unmatched 'else'
+ NDLE)
  >>>>>>> wip-trunk-cleanup
    add_custom_command (OUTPUT resources / share COMMAND mkdir -
  		      p resources /
  		      share) set_source_files_properties (resources /
  							  share resources /
  							  Icon.png resources /
```

That indicates an error in the script (errors from `indent` scattered throughout the output), which will most likely break something somewhere. It seems to affect only `CMakeList.txt` files.

**Comment by charlescurley** [comment]
On Wed, 09 May 2018 14:39:38 +0000 (UTC)
mvglasow <notifications@github.com> wrote:

> About `style=java`, is there any good reason not to use that for all
> files, Java and C alike?

I think I would find it mildly disconcerting to have Java style on C
programs. I am accustomed to having C look like, well, C, and Java like
Java.

Can we have a uniform C style and a uniform Java style? Would two
passes with "find", one for each language, be too onerous?

-- 
"When we talk of civilization, we are too apt to limit the meaning of
the word to its mere embellishments, such as arts and sciences; but
the true distinction between it and barbarism is, that the one
presents a state of society under the protection of just and
well-administered law, and the other is left to the chance government
of brute force."
- The Rev. James White, Eighteen Christian Centuries, 1889
Key fingerprint = CE5C 6645 A45A 64E4 94C0  809C FFF6 4C48 4ECD DFDB
https://charlescurley.com

**Comment by aerostitch** [comment]
I'll have a look for the error you have @mvglasow . I probably missed a parameter that is already declared in my [vimrc](https://github.com/aerostitch/conf_files/blob/master/.vimrc). Do you have the vimrc you used when running the script by any chance?
For the style, I'm adjust to what you prefer as it's more a question of finding a common ground in personal habits. I personally like to have more compact declaration like the  "google" style: http://astyle.sourceforge.net/astyle.html#_style=google but I'm fine with having a java style for java and a more C-like style for C (different languages = different way of seeing how to do things right).
But I'd like to have common rules like on the use of tabs vs spaces and the number of spaces a tab represent at least.

**Comment by mvglasow** [comment]
@aerostitch I do not have any customizations in my `vimrc` (in fact, I do not even have `~/.vimrc` or `~/.vim/vimrc`), so distro defaults apply (Ubuntu 18.04, no idea how heavily `vimrc` is customized by distros).

**Comment by pgrandin** [comment]
> I realize the programming guidelines on our wiki mention K&R style, but that isn’t set in stone, and if we are to change it, it is easiest to do that now.

I personally prefer the one liner too, but we'd need to get feedback from everybody if we were to change that now (and now that @aerostitch is reformatting the code is probably our last chance to do it).

**Comment by jandegr** [comment]
I like to follow a leading authority for styling

for Android-java this is the one https://source.android.com/setup/contribute/code-style

Navit wiki says for C it is K & R
but I would personally not mind if another one was chosen for C with a more complete description.
A random sample https://users.ece.cmu.edu/~eno/coding/CCodingStandard.html

Just don't be tempted to choose an existing style and make variations on it, Navit is just too small an organization to make its own custom style.

**Comment by aerostitch** [comment]
@mvglasow could you either push your resulting branch or come on a chat system please? I'm having trouble reproducing your issue right now in a blank Ubuntu 18.04 docker container and I'd like to avoid to pollute too much this thread with debugging that issue.

Concerning the style choice, I'd like to hear @sleske's opinion has he has been contributing a bunch to the style guide in the wiki.
Basically we'd need an agreement on:
* use tab or spaces (and if spaces, how many do an indentation)
* put the braces at the end of the line or on a new line
* put the return type on a line separated from the rest of the function declaration

Based on that we can choose one of the standard styles for C and C++.

**Comment by aerostitch** [comment]
To make it easier for everyone I made a google form: https://goo.gl/forms/eQ5FY18Fj5LwEscE2
Just answer in it and we'll choose the style based on the responses we have there.
The survey will be closed on May 18th. Please don't answer at the last minute, it's just 5 questions with radio-buttons to click, should take 30seconds max.
Thanks

**Comment by mvglasow** [comment]
@aerostitch I’ve pushed the results of running the cleanup script on `trunk` to [mvglasow/wip-trunk-cleanup](/mvglasow/navit/tree/wip-trunk-cleanup) (and just got the notifications from CircleCI that the builds are failing one by one).

**Comment by aerostitch** [comment]
Sorry I've been busy, I'll try to have a look in the next few days. Thanks for pushing that!

**Comment by aerostitch** [comment]
@mvglasow I'm able to reproduce the issue but due to the fact that the trunk branch of your repo is 168 commits behind navit-gps/navit:trunk. Did you update your trunk locally?

Provided that you already did setup your remote upstream, could you retry after syncing your trunk if you haven't before please?
Doc for configuring your upstream: https://help.github.com/articles/configuring-a-remote-for-a-fork/
Doc for updating your fork: https://help.github.com/articles/syncing-a-fork/

**Comment by mvglasow** [comment]
@aerostitch Yes, I updated trunk locally (if you look at the history, you will see that it is still up to date with trunk). I have both repos (navit-gps and my own) configured as remotes locally; branches which are also in the official repo get updated infrequently in my own repo.

**Comment by mvglasow** [comment]
ps: even after running the cleanup against my own branch, I get few (and easily resolvable) conflicts. It’s only the `CMakeLists.txt` that give me trouble.

**Comment by aerostitch** [comment]
Oh, sorry I understood just now that you were merging `wip-trunk-cleanup` in your config.

I see now that your issue is what has been changed here: https://github.com/mvglasow/navit/commit/11c25a68a0f48e4881a77198096019808dc5371a#diff-af3b638bc2a3e6c650974192a53c7291R723
I have no idea yet why this has changed this way, It doesn't do it for me, even if I run a docker ubuntu 18.04 with no specific configuration, just install git and vim, run the 2 last commands.

But one thing I'm sure is that the last command was not applied properly as there are still a combination of tabs and spaces (you can see them using `:set list` in vim).
Could you, on the `wip-trunk-cleanup` branch, do the following:
* `git reset --hard HEAD^` to remove the last cleanup commit
* Run just `find . -iname 'CMakeLists.txt' -exec ex +"set syn=cmake" +"set noexpandtab" +"norm gg=G" -cwq {} \;` (no commit)
* open the `CMakefile.txt` with vim and use `:set list` to see if there are still a mix of spaces and tabs
* in `CMakelist.txt` look for `compose_xslt_transform_command` and check if the indentation is all weird after that like it is in your current one
* commit and see if anything changed

Also:
* do you have any git hooks in your repo (located in `.git/hooks/`) that would do some reformatting using indent or astyle (that would definitely be an issue)?
* did you run the script by copy-pasting its content or did you run the script as a real script? (I tried both and I still can't reproduce the problem but at least we'd start on common ground)
* what shell do you use? (I'm wondering if there would not be a char escaping that would change between interpreters)

Thanks for your patience.

**Comment by mvglasow** [comment]
I just tried the steps you described.

* There is no file named `CMakefile.txt`. In case you meant `CMakeLists.txt` (the only file in the root dir of the source tree starting with `CMake`): that file still seems to have a mix of tabs (`^I`) and spaces
* In the same file, `macro (compose_xslt_transform_command CMDVAR XSLT_FILE SRC_XML DEST_XML)` is indented with four spaces, no tabs; this is the only occurrence of `compose_xslt_transform_command` in that file
* Most of the file has changed; only a handful of lines have not. (Let me know if you would like me to push this, either to the same or another branch.)
* I have no git hooks (at least I did not knowingly create any)
* I ran the script as a real script
* Shell is bash

**Comment by aerostitch** [comment]
Thanks a lot for those details and sorry for the late reply.

> There is no file named CMakefile.txt. In case you meant CMakeLists.txt

Yes, sorry my bad I meant `CMakeLists.txt`

I have no idea why it does that on your environment, so to avoid making you loose more time I pushed the cleaned up version to the `aerostitch-cleanup-pr569` branch in navit-gps/navit. Could you try to `git merge upstream/aerostitch-cleanup-pr569` on your traffic branch in your own repo after doing a `git fetch upstream` please?

Seeing that the `CMakeLists.txt` reformat is not always reproducible depending on the environment I propose that I'll take care of verifying that manually before each releases and just have a regex that checks for spaces vs tabs in the indentation part of the line when we'll work on the sanity check script.
Would you be ok doing it that way?

Note: I updated my this PR with the current results of the survery (seems for now 80% of the people prefers everything on one line and 4 spaces instead of tabs). The style `attach` should match this and allow both Java and C/C++ users to be happy I'd say. The new script I use is:
```bash
find . -type f  \
 \( -not -path './navit/support/*' -a -not -path './navit/fib-1.1/*' \) \
 -a \( -iname '*.c' -o -iname '*.cpp' -o -iname '*.java' \) \
-exec \
 astyle --indent=spaces=4 --style=attach -n --max-code-length=120 {} \;
# git commit -am 'cleanup:global:Use astyle to reformat everything'

find . -type f \( -not -path './navit/support/*' -a -not -path './navit/fib-1.1/*' -a -not -path './.git/*' \) \
  -a \( -not -iname '*.bat' \) | while read f; do \
   [[ "$(file -bi $f)" =~ ^text ]] && sed 's/\s*$//' -i $f; done
# git commit -am 'cleanup:cmake:remove trailing spaces'

find . -iname 'CMakeLists.txt' -exec ex +"set syn=cmake" +"set noexpandtab" +"norm gg=G" -cwq {} \;
# git commit -am 'cleanup:cmake:retab all CMakeLists.txt files'
```

Let me know what you think,
Thanks
Joseph

**Comment by mvglasow** [comment]
Sorry for the late reply—I tried merging `upstream/aerostitch-cleanup-pr569` into my traffic branch (without performing a local cleanup) and get a long list of conflicts.

As for `CMakeLists.txt`: as I understand it so far, the cleanup stuff is going to be a pre-commit hook which will run against the code before it gets committed, and your proposal is not to change `CMakeLists.txt` in this step, correct? If that is what you had in mind, it probably makes sense (at least until we’ve figured out why I am getting these errors). That would mean eliminating the last line from the script, correct?

As for merging `traffic`, I guess it is going to be easiest if I simply run the cleanup script (not touching `CMakeLists.txt`) on my branch and then merge the cleaned-up `trunk` (all of this after merging the last pre-cleanup commit on `trunk` first). At most, this should give me some conflicts in the two `CMakeLists.txt` (IIRC there were also conflicts where I changed existing code in the *.c files, but they were easy to resolve).

**Comment by lains** [comment]
@mvglasow, if I understood well, the process you're suggesting is:
* Get informed of the official date for the cleanup.
* Merge the upstream trunk onto the local fork's trunk just before the re-indent cleanup (even if the date of the cleanup has already passed, merge on the commit just before it was done)
* Merge the local trunk into the WIP local branch
* Manually apply the re-indent cleanup on the WIP local branch
* Commit this locally on the WIP local branch
* Merge the upstream trunk to the local fork's trunk just after the re-indent cleanup.
* Merge the local fork's trunk into the WIP local branch. During this merge, just keep the local WIP branch as is (discard anything from the trunk as the local branch is already indented)
* Continue to work with the new indentation guidelines
* When submitting the PR, the only changes highlighted should be the actual new code, all indenting will be identical between upstream and local fork.

**Comment by mvglasow** [comment]
@lains pretty much, yes. As for 

> During this merge, just keep the local WIP branch as is (discard anything from the trunk as the local branch is already indented)

Presumably that’s what’s going to happen, though I’d want to look at every conflict in detail just to be sure.

**Comment by aerostitch** [comment]
Sorry for the late reply.

> I tried merging upstream/aerostitch-cleanup-pr569 into my traffic branch (without performing a local cleanup) and get a long list of conflicts.

That's really weird, I don't understand why, I get only a few number of files when I do it. :(

> As for CMakeLists.txt: as I understand it so far, the cleanup stuff is going to be a pre-commit hook which will run against the code before it gets committed, and your proposal is not to change CMakeLists.txt in this step, correct? If that is what you had in mind, it probably makes sense (at least until we’ve figured out why I am getting these errors). That would mean eliminating the last line from the script, correct?

Well, the pre-commit hook works one file at a time, but the idea will be similar, yes.
But yes, that is correct, that my proposal will be not to include the `CMakeLists.txt` files cleanup on that step.

> As for merging traffic, I guess it is going to be easiest if I simply run the cleanup script (not touching CMakeLists.txt) on my branch and then merge the cleaned-up trunk (all of this after merging the last pre-cleanup commit on trunk first). At most, this should give me some conflicts in the two CMakeLists.txt (IIRC there were also conflicts where I changed existing code in the *.c files, but they were easy to resolve).

Yep, not touching the `CMakeLists.txt` is better.

> Get informed of the official date for the cleanup.

I'll do that as soon as I get an approval on the current PR.


Now the results of the survey:
* 100% of the responses indicated 120 chars as preferred line length
* 80% indicated 4 chars as preferred indentation both for C and Java files
* 80% prefer open brackets on the same line as the function name (for C)
* 100% prefer the return type of the function on the same line as the function named (for C)

I just updated the branch of this PR with the latest trunk updates and the coding style above (attach style in astyle).

**Comment by mvglasow** [comment]
> > I tried merging upstream/aerostitch-cleanup-pr569 into my traffic branch (without performing a local cleanup) and get a long list of conflicts.
>
> That's really weird, I don't understand why, I get only a few number of files when I do it. :(

Due to the nature of the conflicts, I suspect this is because one branch was missing a few commits from `trunk`.

> my proposal will be not to include the `CMakeLists.txt` files cleanup on that step

Sounds good to me.

**Comment by jandegr** [comment]
Hi,

Can I assume that the 120 chars linelength and 4 spaces for a tab from the results of the survey are the final choice ?

Can astyle be set to a double tab for linewrap ?
https://source.android.com/setup/contribute/code-style#use-spaces-for-indentation

thx.

**Comment by aerostitch** [comment]
Hi,

> Can I assume that the 120 chars linelength and 4 spaces for a tab from the results of the survey are the final choice ?

Yes you can!

**Comment by aerostitch** [comment]
Cool, thanks.
Unless anybody disagrees I'm going to merge this PR on May 25th at 4PM Pacific time.

**Comment by mvglasow** [comment]
Quick one, what about commits made in the meantime (I see the reindent-everything branch is one commit behind trunk at this time)? Will they still get merged before?

I would suggest we hold back other commits and merges for the rest of the day, until the cleanup has been merged—things might get messy otherwise.

BTW (as I just had to look that up myself), 16:00 PDT = 23:00 UTC.

**Comment by aerostitch** [comment]
> Quick one, what about commits made in the meantime (I see the reindent-everything branch is one commit behind trunk at this time)? Will they still get merged before?

I'll rebase on trunk just before merging.

> I would suggest we hold back other commits and merges for the rest of the day, until the cleanup has been merged—things might get messy otherwise.

yes that would be ideal

**Comment by aerostitch** [comment]
Sorry I'm 6 hours late.
I'll merge at the end of the circleci build.
I'll push some PR for a sanity check job in circleci tomorrow or Sunday and a pre-commit hook proposal with instructions in another PR.

**Comment by aerostitch** [comment]
PR merged!

**Comment by jandegr** [comment]
Hi,
Checkstyle for Java seems to have 240 extra warnings but it could as well be that checkstyle itself has to be tuned a little more, however there are a few strange issues

sample

https://github.com/navit-gps/navit/blob/trunk/navit/android/src/org/navitproject/navit/NavitSensors.java#L42

**Comment by mvglasow** [comment]
Thanks for the work you did!

I have cleaned up the traffic branch locally, and things largely worked as I expected them to.

`CMakeLists.txt` got reformatted, but with two spaces instead of tabs. Can you re-post the exact command lines you used? I used the ones you posted above (also found in the script in my repo), has anything changed about them?

Eventually, I was able to resolve the resulting conflicts (resolving them in favor of `trunk`, then re-applying the few actual modifications introduced in my branch).

Conflicts in C files were a bit less obvious and I resolved them after reviewing each one manually. Mostly that was in favor of the local branch, but the diffs often weren’t obvious, as git reported a couple of conflicts in which large parts of both hunks appeared to be identical in the end.

Merge strategy here in a nutshell:
* Have I changed the file in my branch?
  * No → Use remote version (i.e. `trunk`)
  * Yes →Do all of the conflicts refer to code I changed in my branch? (If in doubt, look at local branch history.)
    * Yes → Use local version (i.e. from own branch)
    * No → Use a diff tool to evaluate and resolve each conflict individually

I just built my branch and ran my test cases, and everything seems OK. (Strategy above can be considered battle-hardened, as the `traffic` branch is one of the more complex test cases.)

**Comment by aerostitch** [comment]
@jandegr that is indeed really strange. We'll have to dig deeper.

@mvglasow the "2 spaces instead of tabs" thing leads me to believe there's something in your vim config that overwrites the command-line arguments. In the command-line the `noexpandtab` is used to avoid using spaces instead of tabs. Here's the command I used to reformat the `CMakeLists.txt`:
```
find . -iname 'CMakeLists.txt' -exec ex +"set syn=cmake" +"set noexpandtab" +"norm gg=G" -cwq {} \;
```
I copy/pasted the command-lines from https://github.com/navit-gps/navit/pull/569#issuecomment-388670966 to reformat.

**Comment by aerostitch** [comment]
Yep, that's why I'm not using it in https://github.com/navit-gps/navit/pull/603

**Comment by jandegr** [comment]
See comment in  https://github.com/navit-gps/navit/pull/603 about the linelength or codelength

**Pull request merged**
