### PR TITLE
translated messages in ja.po.

### PR DESCRIPTION
**Pull request by thortex**
I translated messages in po/ja.po.in for Japanese users.
Could you merge this changed file?

### CODE REVIEW

**Comment by metalstrolch** [comment]
Looks OK for me, although I have no clue about Japanese.
OK to merge.

**Comment by pgrandin** [comment]
Thanks @thortex !

Our usual workflow for translation is to use launchpad : https://translations.launchpad.net/navit 

Our translation template (navit.pot) is automatically updated from our CI, and we have tools to merge changes from launchpad back in git.

We can't merge your PR directly has it might overwrite or conflict with changes in Launchpad, but I will upload your .po file to launchpad and merge it.

Thanks for your contribution!

**Comment by thortex** [comment]
I appreciate to your explanations, pgrandin.
I did not know the workflow (launchpad, CI, and merge tools), so I directly did send PR.

Thank you for your merge to launchpad in advance.
I'll use launchpad next time.

**Comment by pgrandin** [comment]
Thanks @thortex 
I'll make sure that the relevant wiki page is up to date too.

I tried to merge your the Japanese translation update but the tests are failing:
```
[ 97%] Generating ja.mo
/home/ubuntu/android-arm/po/ja.po:92: number of format specifications in 'msgid_plural' and 'msgstr[0]' does not match
/home/ubuntu/android-arm/po/ja.po:97: number of format specifications in 'msgid_plural' and 'msgstr[0]' does not match
/home/ubuntu/android-arm/po/ja.po:118: number of format specifications in 'msgid_plural' and 'msgstr[0]' does not match
/home/ubuntu/android-arm/po/ja.po:123: number of format specifications in 'msgid_plural' and 'msgstr[0]' does not match
/usr/bin/msgfmt: found 4 fatal errors
```
https://circleci.com/gh/navit-gps/navit/1742

We've had the same issue before with other languages, I will have to check what is going on. I think that we are missing an msgstr for the plural form.

Here is an example:
```
#, c-format
msgid "one kilometer"
msgid_plural "%d kilometers"
msgstr[0] "1 km"
```

**Comment by thortex** [comment]
Thank you for your building/testing.

Sorry, I did not specify "--check" option to msgfmt command for format checking.

Generally, Japanese has no plural forms, but number of plurals should be specified to 2, and plural condition should be specified to "n > 1" in msgfmt header parameters for CI/merge automation tools as the following link :
https://github.com/thortex/navit/commit/020753d95930017682d500654e3ae9c4a5667853#diff-cb0342827b59cfacd6050789fa0dc0a4R18

And plurals are described at line number 93, 99, 121, and 127 in the ja.po.in:
https://github.com/thortex/navit/blob/020753d95930017682d500654e3ae9c4a5667853/thortex/ja.po.in#L93

**Comment by thortex** [comment]
I merged GitHub changes to launchpad ja.po file, and uploaded the file into Import queue: https://translations.launchpad.net/navit/trunk/+imports

**Comment by jkoan** [comment]
I close this PR now. Thanks for your support.

**Pull request closed without merging**
