### PR TITLE
Add/Android: Provide geo coordinates for clicked position in contextual menu

### PR DESCRIPTION
**Pull request by lains**
When performing a short clicking/tap on an point on the map, in Android, a contextual menu is opened.
This menu mainly allows to start navigation to the point that has just been clicked on.
This PR adds two features:
* it adds the geographical coordinates of the point clicked on the map in the contextual menu title:
Screenshot_Navit_20190613-085619

* and it fixes the displayed name of the location in the destination history (before it used screen coordinates as a bookmark names, which does not make much sense for the final user, and was partially broken, as only X coordinates were used).
The screenshot below allows to compare both the new destination name format (top), and the old destination format (second entry named "334"):
Screenshot_Navit_20190613-085808

In addition, this PR also adds a mechanism to escape and unescape double quotes (") in text files (required to store geographical coordinates, as they use character (") for seconds).

### CODE REVIEW

**Comment by lains** [comment]
This PR cannot be merge for now because it is based on an old trunk revision.
Unfortunately, I cannot rebase on the latest version of trunk because of https://github.com/navit-gps/navit/issues/802

**Comment by lains** [comment]
This PR has been rebased on the latest trunk, including the fix for Android build (https://github.com/navit-gps/navit/commit/c2f9838f07a52cc64cb05e9cf95bb378261946d9).

**Comment by lains** [comment]
PR rebased on current trunk and is ready for merge. Should probably be merged before https://github.com/navit-gps/navit/pull/812 (that also includes this code).

**Comment by lains** [comment]
This is a prerequisite for #812.
Anyone against merging this? If not, I will rebase and merge (probably next week-end... September 21-22nd)

**Comment by jandegr** [comment]
Hi,

A small note on the JNI signature 
`int` must be `jint` and the name must be `Java_org_navitproject_navit_NavitGraphics_getCoordForPoint`

and in java change the name as well and private will do
`private native String getCoordForPoint(int id, int x, int y);`
otherwise an extra codefactor issue for the name :)

for the rest you might have a too long line here or there, checks on CI do not verify linelength but codefactor will bite.

I will merge a part of the code to test so I might come back on this but that won't be before tomorrow or so.

thx.

**Comment by lains** [comment]
Hi @jandegr, thanks for your feedback. I'll have a look at these items.

**Comment by lains** [comment]
CircleCI sanity check passed. CodeFactor did find style issues including lines that are too long, but these are not related to the changes included by this PR, so I'd rather not mix current changes with unrelated style updates.

**Comment by lains** [comment]
Will soon (probably tomorrow) rebase and squash merge... unless anyone is against it...

**Pull request merged**
