### PR TITLE
Fix Car layout issues with wood and water

### PR DESCRIPTION
**Pull request by jfitie**
Fixed some issues in ```Car``` layout where wood (```poly_wood```) was not showing up correctly inside towns (```poly_town```) and water (```poly_water```) was missing in parks (```poly_park```). Also fixed some discrepancy issues in the ```Car-dark``` layout.

### CODE REVIEW

**Comment by jfitie** [comment]
2 example images. Sorry about the DPI differences between _before_ and _after_.

screenshot_2017-05-06-19-32-44
screenshot_2017-05-06-19-33-03

screenshot_2017-05-06-19-33-27
screenshot_2017-05-06-19-33-34

**Comment by pgrandin** [comment]
Bonus points for the screenshots. Thanks a lot!

**Comment by jandegr** [comment]
Hi,
There is indeed some work to do to tune the layouts, but in this case moving water_tiled is not helping for the samples you show and will probably worsen flooded maps.
In such areas we now see roads and such on top of a watersurface, with the move of water_tiled I think they will get drowned completely. Will try to come up with some samples, stay tuned.

**Comment by jandegr** [comment]
A flooded sample before [https://167-32961764-gh.circle-artifacts.com/0/tmp/circle-artifacts.1cS0lMk/Boulevard_Peripherique_2.yamlmetric.png](url)
The same but with today's trunk [https://216-32961764-gh.circle-artifacts.com/0/tmp/circle-artifacts.k7RETdG/Boulevard_Peripherique_2.yamlmetric.png](url)

Long live QA

**Comment by jfitie** [comment]
Should I move ```poly_water_tiled``` back and keep the other changes?

**Comment by jandegr** [comment]
Yes I think so, but why not leave the PR open a little longer before merging and fix some other stuff in the layouts as well at the same time ?
In case you would be interested (and willing) to get the layout in a better shape we can add some missing stuff in the maps as well, as a sample see the commits for sand, grass, wetland and so I tested.
https://github.com/jandegr/navit/commits/ext_graph_prep/navit/maptool/osm.c

**Comment by jandegr** [comment]
IIRC there items converted by maptool that don't have an entry in the layout eiter. 
https://github.com/navit-gps/navit/blob/trunk/navit/maptool/osm.c#L663

**Comment by jfitie** [comment]
@jandegr Just did a quick delta between what's converted by maptool and what's shown in the Car layout.

? elevation
? poi_baseball
? poi_basketball
? poi_bicycle_parking
? poi_bicycle_rental
? poi_climbing
? poi_guesthouse
? poi_hairdresser
? poi_hostel
? poi_kindergarten
? poi_motel
? poi_motor_sport
? poi_nightclub
? poi_playground
? poi_prison
? poi_recycling
? poi_school_college
? poi_school_university
? poi_shop_baker
? poi_shop_beverages
? poi_shop_butcher
? poi_shop_drugstore
? poi_shop_florist
? poi_shop_fruit
? poi_shop_kiosk
? poi_shop_optician
? poi_shop_parfum
? poi_shop_photo
? poi_shop_shoes
? poi_soccer
? poi_tennis
? poi_tree
? poi_vending_machine
n barrier_bollard
n barrier_cycle
n barrier_lift_gate
n poi_toll_booth
n power_substation
n power_tower
n traffic_sign_city_limit
n traffic_sign_stop
w border_civil
w border_national_park
w border_political
w bus_guideway
w city_wall
w ditch
w fence
w hedge
w house_number_interpolation_all
w house_number_interpolation_alphabetic
w house_number_interpolation_even
w house_number_interpolation_odd
w poly_airfield
w poly_allotments
w poly_archaeological_site
w poly_artwork
w poly_attraction
w poly_barracks
w poly_basin
w poly_battlefield
w poly_beach
w poly_brownfield
w poly_camp_site
w poly_caravan_site
w poly_college
w poly_commercial
w poly_common
w poly_construction
w poly_danger_area
w poly_fell
w poly_fishing
w poly_garden
w poly_glacier
w poly_golf_course
w poly_greenfield
w poly_heath
w poly_landfill
w poly_marina
w poly_marsh
w poly_mud
w poly_nature_reserve
w poly_naval_base
w poly_picnic_site
w poly_place1
w poly_place2
w poly_place3
w poly_place4
w poly_place5
w poly_place6
w poly_playground
w poly_plaza
w poly_quarry
w poly_railway
w poly_range
w poly_recreation_ground
w poly_reservoir
w poly_retail
w poly_ruins
w poly_scree
w poly_sports_stadium
w poly_sports_track
w poly_theme_park
w poly_village_green
w poly_water_park
w poly_zoo
w powerline
w rail_abandoned
w rail_disused
w rail_light
w rail_mono
w rail_narrow_gauge
w rail_preserved
w rail_subway
w retaining_wall
w street_construction
w wall

**Pull request merged**
