### PR TITLE
Android platform tools workaround

### PR DESCRIPTION
**Pull request by jkoan**
This pull request adds a workaround to the CI because current platform tools from google are broken.
This fixes Ticket #1354

### CODE REVIEW

**Comment by aerostitch** [comment]
We were woeking with @pgrandin on the branch google_play to upgrade to the new sdk commands as the current ones are deprecated. Might be a longer term approach. Currently the only problem left lies in the order of the include directives.

**Comment by aerostitch** [comment]
Note that you're more than welcome to give a new eye on this branch @jkoan ;)
Sorry I was supposed to update the ticket yesterday but got bumped with work.

**Comment by jkoan** [comment]
I will defensively look into it, but the fix (see #357 ) only for the time until the new command is ready.
I have spoken to @pgrandin about that. He pushed me to do this PR ;)

**Comment by pgrandin** [comment]
Yeah we definitely need to finish the work in the google_play branch as the `android` command is deprecated, but at least we can still build and release until we figure out the issue @aerostitch just mentioned.

**Pull request closed without merging**
