### PR TITLE
Make Image and Scale osd types obey osd_configuration setting

### PR DESCRIPTION
**Pull request by pohlinkzei**
This PR shall fix [trac-1202](http://trac.navit-project.org/ticket/1202)

### CODE REVIEW

**Comment by pohlinkzei** [comment]
I've found an issue I have to investigate before merging. So please wait. ;)

**Comment by pgrandin** [comment]
:)

I tried to test this yesterday but my osd_configuration was not behaving as I expected...

**Comment by pohlinkzei** [comment]
If you add use_overlay="1" to the osd, it works as expected.

**Comment by pgrandin** [comment]
@pohlinkzei : any update? Thanks!

**Comment by jkoan** [comment]
@pohlinkzei and @pgrandin since this is not working and no work is done to do so what's about close this PR?

**Comment by sleske** [comment]
@jkoan : Good idea. Done. We can always reopen later.

**Pull request closed without merging**
