### PR TITLE
Qt5 Graphics: Add QML support

### PR DESCRIPTION
**Pull request by metalstrolch**
This pull request is about adding QML (QtQuick) Support to graphics_qt5 plug in.
A QML based graphics back plug in allows:
 a) to easily add a QML based GUI
 b) to integrate navit to Jolla Sailfish OS once, since QWidgets library is banned in Sailfish's Harbour shop.
This adds two build flags:
USE_QWIDGET:BOOL --> Enable QWidgets support (autodetected)
USE_QML:BOOL --> Enable QML support (autodetected)
Both can be set at the same time.

This adds one attr to graphics section in navit.xml:
qt5_widget -> set to "qml" for QML display, set to "qwidget" for qwidget display. Must only be set if both methods are present at the same time.

### CODE REVIEW

**Comment by metalstrolch** [comment]
What's the official documentation for attrs, as we should document graphics_qt5's attrs once this is merged?
Do we have a Navit coding style? Or is it OK to just process the Qt5 plugins with clang-format.

**Comment by pgrandin** [comment]
Thanks @metalstrolch nice work!
I am really happy to see tangible progress towards QT5 and a new QML UI!

Your PR looks good to me, but maybe we would want to address this before merging :
https://1713-30791823-gh.circle-artifacts.com/1/tmp/circle-artifacts.UuE0TvX/logs_qt5_qml/stderr.txt
```
error:navit:convert_to_attrs:failed to create attribute 'v' with value '792'
QQmlApplicationEngine failed to load component 
qrc:///graphics_qt5.qml:-1 File not found
 ```
Regarding your questions about attributes, I think that this is the kind of thing that we should document in both doxygen and the wiki. Unfortunately the wiki is down right now...

**Comment by metalstrolch** [comment]
This is fixed now. It builds (and runs) in CI. The Gifs look silly for both the QT5 GUIs test runs because qt5 seems to miss keyboard support. Since this was not introduced with this change I'll fix this in another PR.

**Comment by metalstrolch** [comment]
Picked the wrong button... Of course still open.

**Comment by pgrandin** [comment]
Thanks @metalstrolch really nice work here.
Looks good to me!

**Pull request merged**
