### PR TITLE
Icon dam

### PR DESCRIPTION
**Pull request by youte62**
dam-montage 1

### CODE REVIEW

**Comment by metalstrolch** [comment]
Force pushed this, removing already merged old commits to resolve conflict.

**Comment by metalstrolch** [comment]
Looks way better than than previous version in #324. But as mentioned there, think of adding a contrasting colour (either black or white typically, depending on how dark the icon is) outline to the symbols.
Have a look to the screenshots posted by me on #324. On the POI screen, you clearly see the white outline making the mostly black old icons work on the black background.
This is not "as much" a problem with this icon, as there is seldom any "all blue" background, but it would give more contrast having a, white in this case, outline on a black backgrounded screen.

**Comment by pgrandin** [comment]
I rebased @youte62 's branch, and will work with him to fix the other PRs.
Green light for this one?

**Comment by metalstrolch** [comment]
OK for me. Except i did not mean putting a solid background behind the symbol for outline. But that's OK for now.

**Comment by pgrandin** [comment]
I actually like your idea of using an outline instead of a background. 
@youte62 what do you think?

**Pull request merged**
