### PR TITLE
Icon communication

### PR DESCRIPTION
**Pull request by youte62**
communication-montage

### CODE REVIEW

**Comment by metalstrolch** [comment]
Force pushed this, removing already merged old commits to resolve conflict.

**Comment by sleske** [comment]
@youte62 : I really appreciate all these icons you are creating, however some confuse me a bit. What is the purpose of this icon in Navit? Is it supposed to be shown on the map? In a menu? While it's good to have nice icons, there's little point in including them in Navit without knowing what to use them for. So what is your goal?

**Comment by youte62** [comment]
I was asked to create icons missing. What I'm doing, later I do not know where it will be used.

**Comment by sleske** [comment]
@youte62 : Thanks for the explanation. I just saw there is actually a POI type "communication" in Navit (though it's only used by the Garmin map driver), so we may be able to use the icon.

**Pull request merged**
