### PR TITLE
Add backers and sponsors from Open Collective

### PR DESCRIPTION
**Pull request by piamancini**
Now your open collective backers and sponsors can to appear directly on your README. 
see how it'll look [here](https://github.com/apex/apex#backers)
[More info](https://github.com/opencollective/opencollective/wiki/Github-banner)
Also add badges on top

### CODE REVIEW

**Comment by metalstrolch** [comment]
Spam?

**Comment by pgrandin** [comment]
Actually not it's legit :)
We were approved to join http://opencollective.com/ (we are at https://opencollective.com/navit )

I think that we don't have a use for sponsors yet. We'll have to discuss the details with the community.

**Comment by sleske** [comment]
Sorry, but this PR is definitely not something I'd merge. It bloats our README.md with links to 30 (!) sponsors and backers each - which do not (yet) exist. First we'll have to figure out how we can/want to use OpenCollective, then we need backers, then we can decide if and how to put them in our README.

**Comment by piamancini** [comment]
Hi @sleske @pgrandin 
That's valid, you can then decide how to display backers. Quick question, you've applied to open collective and so have a live collective opencollective.com/navit and can already receive contributions. Do you want us to close it until you figure it out? Best

**Comment by pgrandin** [comment]
Hi Pia,

I'd like to keep our collective open. We haven't really worked on advertising it yet but we should do it soon.

Thanks!

**Comment by sleske** [comment]
@piamancini , @pgrandin : Just to clarify - I did not want to judge our involvement with Open Collective in any way. I just closed this PR because as a PR it is not suitable for merging.

We can and should further discuss our cooperation with Open Collective - it's just that I don't feel this is helped by permanently keeping a PR open. So let's see how we can work together.

**Comment by piamancini** [comment]
sounds good! We'll keep your collective open. Just note please that the default tiers state that sponsors and backers will show up in readme. We should probably remove that if you don't plan on doing it. Whenever you are ready, there's no rush to do this.

**Pull request closed without merging**
