### PR TITLE
Fix:android:64 bit and cleanup2

### PR DESCRIPTION
**Pull request by jandegr**
A cleaned version as a followup on
#863

Many more fixes to do but I have to draw a line from time to time

after this you may have to set autobrief on doxygen if not already so
`If the JAVADOC_AUTOBRIEF is set to YES then doxygen will interpret the first line (until the first dot) of a JavaDoc-style comment as the brief description.`

fixes https://github.com/navit-gps/navit/issues/828
fixes https://github.com/navit-gps/navit/issues/832
fixes https://github.com/navit-gps/navit/issues/550

### CODE REVIEW

**Comment by jandegr** [comment]
a test on a MI A2  with STF

1cc1a437

1cc1a438

**Comment by jandegr** [comment]
Hi,
Solved the merge conflict and included the "send geo intent" part of https://github.com/navit-gps/navit/pull/812 all credits to @lains 

STF @pgrandin is quite slow right now, so the screenshot is from a local jellybean device this time,
showing the selection popup after launching a geo intent from Navit.

Screenshot_2019-09-24-12-19-08

**Comment by lains** [comment]
> @lains sending an intent works flawless, I just had the impression smth in #812 is only 95% identical to #794 but I could not resist testing it. Manifest already registers Navit as a receiver but obviously that won't work yet since the code itself is not included, but I tweaked the sending part so that it requires more than one receiving app to prevent sent intents from just being looped back to Navit. What are your thoughts about all of this ?

@jandegr, yes you're perfectly right. #794 (now merged) was already containing features that were re-used for #812.
I am planning to merge #812 soon, so that you can rebase on trunk... and you're right also that looping geo: view intents back to navit is not a good thing...

**Comment by lains** [comment]
@jandegr, what do you prefer?
Shall #812 be squash-merged and you rebase on trunk?
Or do you want to submit #877 containing all changes (maybe not as good because in the history, both features will be mixed, which makes it more difficult to debug).

Both ways suit me, in case you go for option 1, #812 is ready for merge to trunk, so either you can go ahead or post me review comment on #812 to have me perform the merge.

**Comment by jandegr** [comment]
Hi @lains 
You're completely free to handle it as you want, this pr just shows how I think things can be handled and I doubt any of it will make it into trunk as such. In the case of the geo intent sending I just showed it in advance instead of waiting until it was committed.

**Comment by jandegr** [comment]
Hi,

By now I started reworking other stuff so I did a final and last commit on this PR.
Removes receiving geo intents, that was very interesting and gave a preview of what issues to expect so I limited it to sending geo intents for now (credit to @lains).
And a some last minor cleanup.

Known issues 
- colors in the filebrowseractivity not ok on android 2.3 as reported by @jkoan 
- fullscreen to be reviewed
- in landscape mode the native keyboard leaves little room for gui_internal, removing the numerical bar could improve things a bit.

The system bars become solid instead of transparent while dragging the map, a limitation of graphics not being informed by navit that it changes from mapview to gui_internal, subject to improvement.

Several other improvements and fixes of mostly longstanding issues were not handled and could be done in smaller PR's.

Testing was done 
- locally on 4 devices and 3 AVD's
- 2 devices on Kobiton
- 2 devices on STF @pgrandin THX!
- several tests done by @jkoan THX! 

Bumps it from B to A- on codefactor, but at the rate new issues are created that won't last long.

**Pull request merged**
