### PR TITLE
Update:Navit logo according to proposal in issue #436

### PR DESCRIPTION
**Pull request by lains**
Updating navit logo icon as proposed in issue #436.
Changing GTK GUI to use this logo on window.
Using this logo as the icon for the Action menu in the internal GUI:
navit_new_transp

### CODE REVIEW

**Comment by mvglasow** [comment]
Looks good, except that I personally would leave the Actions icon as is. (In fact, the menu/UX is in need of a redesign as well, but that is way out of scope here.)

**Comment by zintor** [comment]
It looks also good to me. I am also with mvglasow, that it sould be a logo replacement and not a redesign of menu/UX.
As pointed, there are more ressources of changing the logo. There is a [wiki page](https://wiki.navit-project.org/index.php/Logo), which we could use to summarize where the logo should be exchanged. Please feel free to use the page. When we do not forget a location.

**Comment by lains** [comment]
I've excluded the update in the internal GUI from this PR.
I agree that a more global redesign of the Internal GUI wuld be required, various actions are using the same icon, and this created some confusion to me when I first used this software.

I also switched to a black logo for the GTK UI for better readability (orange over grey was not very good).

navit_new_logo_gtk

**Comment by jkoan** [comment]
> Looks good, except that I personally would leave the Actions icon as is. (In fact, the menu/UX is in need of a redesign as well, but that is way out of scope here.)

I totally agree with this.

But the GTK UI Icon in black looks good. 
We need to put much more work into UX/UI anyway.

I like the Logo itself (both) but i think we need to redesign even more and meke the look and feel unique across the application.

**Comment by lains** [comment]
I have reverted the icon used for the Action button to the original one [here](https://github.com/navit-gps/navit/pull/724/commits/4b0f5ebd85b16756e4cf78f1acb7d0269ce76f1b), but, yes, I think the design of UI is a wider work.
Can't we first tackle the update of logo/application icon rework, before starting the whole UI rework? This would maybe help to split this huge work into smaller chunks.

**Comment by mvglasow** [comment]
> Can't we first tackle the update of logo/application icon rework, before starting the whole UI rework? This would maybe help to split this huge work into smaller chunks.

Absolutely. Let’s stick with the application logo for this PR, and tackle other UX items separately. I have a few ideas of my own to contribute there. We might want to turn UX redesign into a project to allow us to keep an overview over everything going on, as it involves a bunch of things.

**Comment by lains** [comment]
Hello all,

What shall we do with this PR?
Shall we just merge this new logo, [initially designed by redmusic](https://github.com/navit-gps/navit/issues/436) and reworked+implemented as svg by @zintor?
This PR not only adds the new color svg logo for Navit but also a derived black and white logo for application, and also adds code to make the GTK GUI Windows use that B&W logo as icon.

**Comment by lains** [comment]
Rebased code on trunk.
Also, I intergated to sources, [the svg logo catalog](https://github.com/navit-gps/navit/blob/563b86189811764993ad5add6261610e3e5e520c/logo_catalog.svg) that was last posted in https://github.com/navit-gps/navit/issues/436#issuecomment-450587935

**Comment by lains** [comment]
Anyone against merging this? If not, I will rebase and merge (probably around Wed 18th).

**Comment by mvglasow** [comment]
Looks good to me.

**Pull request merged**
